(** MASC Protobuf Module Coverage Tests

    Tests for autogenerated protobuf types:
    - Empty type
    - Agent type
    - Task type
    - Roundtrip serialization
*)

open Alcotest

module Masc_pb = Masc_mcp.Masc_pb

(* ============================================================
   Empty Tests
   ============================================================ *)

let test_empty_make () =
  let e = Masc_pb.Masc.V1.Empty.make () in
  check unit "empty make" () e

let test_empty_name () =
  let n = Masc_pb.Masc.V1.Empty.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   Agent Tests
   ============================================================ *)

let test_agent_make_default () =
  let a = Masc_pb.Masc.V1.Agent.make () in
  check string "default name" "" a.name;
  check string "default status" "" a.status

let test_agent_make_with_values () =
  let a = Masc_pb.Masc.V1.Agent.make
    ~name:"claude"
    ~status:"active"
    ~capabilities:["code"; "review"]
    () in
  check string "name" "claude" a.name;
  check string "status" "active" a.status;
  check int "capabilities count" 2 (List.length a.capabilities)

let test_agent_name () =
  let n = Masc_pb.Masc.V1.Agent.name () in
  check bool "has name" true (String.length n > 0)

let test_agent_merge () =
  let a1 = Masc_pb.Masc.V1.Agent.make ~name:"a1" () in
  let a2 = Masc_pb.Masc.V1.Agent.make ~status:"active" () in
  let merged = Masc_pb.Masc.V1.Agent.merge a1 a2 in
  (* Merge behavior: later values override *)
  check string "merged status" "active" merged.status

(* ============================================================
   Task Tests
   ============================================================ *)

let test_task_make_default () =
  let t = Masc_pb.Masc.V1.Task.make () in
  check string "default id" "" t.id;
  check string "default status" "" t.status

let test_task_make_with_values () =
  let t = Masc_pb.Masc.V1.Task.make
    ~id:"task-001"
    ~title:"Fix bug"
    ~status:"pending"
    ~priority:1
    () in
  check string "id" "task-001" t.id;
  check string "title" "Fix bug" t.title;
  check int "priority" 1 t.priority

let test_task_name () =
  let n = Masc_pb.Masc.V1.Task.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   BroadcastRequest Tests
   ============================================================ *)

let test_broadcast_request_make () =
  let br = Masc_pb.Masc.V1.BroadcastRequest.make
    ~agent_name:"claude"
    ~message:"Hello world"
    () in
  check string "agent_name" "claude" br.agent_name;
  check string "message" "Hello world" br.message

let test_broadcast_request_name () =
  let n = Masc_pb.Masc.V1.BroadcastRequest.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   Proto Roundtrip Tests
   ============================================================ *)

let test_agent_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Agent.make
    ~name:"test-agent"
    ~status:"active"
    ~capabilities:["cap1"; "cap2"]
    ~last_heartbeat:"2024-01-15T12:00:00Z"
    ~joined_at:"2024-01-15T10:00:00Z"
    () in
  let writer = Masc_pb.Masc.V1.Agent.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Agent.from_proto reader with
  | Ok decoded ->
    check string "name roundtrip" original.name decoded.name;
    check string "status roundtrip" original.status decoded.status
  | Error _ -> fail "proto decode failed"

let test_task_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Task.make
    ~id:"task-123"
    ~title:"Test task"
    ~status:"pending"
    ~priority:2
    () in
  let writer = Masc_pb.Masc.V1.Task.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Task.from_proto reader with
  | Ok decoded ->
    check string "id roundtrip" original.id decoded.id;
    check string "title roundtrip" original.title decoded.title
  | Error _ -> fail "proto decode failed"

(* ============================================================
   Message Tests
   ============================================================ *)

let test_message_make_default () =
  let m = Masc_pb.Masc.V1.Message.make () in
  check string "default id" "" m.id;
  check string "default from" "" m.from;
  check string "default content" "" m.content;
  check int "default seq" 0 m.seq

let test_message_make_with_values () =
  let m = Masc_pb.Masc.V1.Message.make
    ~id:"msg-001"
    ~from:"claude"
    ~content:"Hello world"
    ~timestamp:"2026-02-06T12:00:00Z"
    ~seq:42
    () in
  check string "id" "msg-001" m.id;
  check string "from" "claude" m.from;
  check string "content" "Hello world" m.content;
  check int "seq" 42 m.seq

let test_message_name () =
  let n = Masc_pb.Masc.V1.Message.name () in
  check bool "has name" true (String.length n > 0)

let test_message_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Message.make
    ~id:"msg-rt"
    ~from:"codex"
    ~content:"roundtrip test"
    ~timestamp:"2026-01-15T10:00:00Z"
    ~seq:99
    () in
  let writer = Masc_pb.Masc.V1.Message.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Message.from_proto reader with
  | Ok decoded ->
    check string "id roundtrip" original.id decoded.id;
    check string "from roundtrip" original.from decoded.from;
    check string "content roundtrip" original.content decoded.content;
    check int "seq roundtrip" original.seq decoded.seq
  | Error _ -> fail "message proto decode failed"

let test_message_merge () =
  let m1 = Masc_pb.Masc.V1.Message.make ~id:"m1" ~from:"a" () in
  let m2 = Masc_pb.Masc.V1.Message.make ~content:"hello" ~seq:5 () in
  let merged = Masc_pb.Masc.V1.Message.merge m1 m2 in
  check string "merged content" "hello" merged.content;
  check int "merged seq" 5 merged.seq

(* ============================================================
   Vote Tests
   ============================================================ *)

let test_vote_make_default () =
  let v = Masc_pb.Masc.V1.Vote.make () in
  check string "default id" "" v.id;
  check string "default topic" "" v.topic;
  check int "default required_votes" 0 v.required_votes

let test_vote_make_with_values () =
  let v = Masc_pb.Masc.V1.Vote.make
    ~id:"vote-001"
    ~topic:"Which framework?"
    ~proposer:"claude"
    ~options:["React"; "Vue"; "Svelte"]
    ~required_votes:3
    ~status:"active"
    () in
  check string "id" "vote-001" v.id;
  check string "topic" "Which framework?" v.topic;
  check string "proposer" "claude" v.proposer;
  check int "options count" 3 (List.length v.options);
  check int "required_votes" 3 v.required_votes;
  check string "status" "active" v.status

let test_vote_name () =
  let n = Masc_pb.Masc.V1.Vote.name () in
  check bool "has name" true (String.length n > 0)

let test_vote_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Vote.make
    ~id:"vote-rt"
    ~topic:"Test vote"
    ~proposer:"test"
    ~options:["A"; "B"]
    ~required_votes:2
    ~status:"active"
    () in
  let writer = Masc_pb.Masc.V1.Vote.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Vote.from_proto reader with
  | Ok decoded ->
    check string "id roundtrip" original.id decoded.id;
    check string "topic roundtrip" original.topic decoded.topic;
    check int "options count" 2 (List.length decoded.options)
  | Error _ -> fail "vote proto decode failed"

(* ============================================================
   JoinRequest/Response Tests
   ============================================================ *)

let test_join_request_make () =
  let jr = Masc_pb.Masc.V1.JoinRequest.make
    ~agent_name:"claude-1"
    ~capabilities:["code"; "review"; "test"]
    () in
  check string "agent_name" "claude-1" jr.agent_name;
  check int "capabilities count" 3 (List.length jr.capabilities)

let test_join_request_name () =
  let n = Masc_pb.Masc.V1.JoinRequest.name () in
  check bool "has name" true (String.length n > 0)

let test_join_request_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.JoinRequest.make
    ~agent_name:"test-agent"
    ~capabilities:["cap1"; "cap2"]
    () in
  let writer = Masc_pb.Masc.V1.JoinRequest.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.JoinRequest.from_proto reader with
  | Ok decoded ->
    check string "agent_name" original.agent_name decoded.agent_name;
    check int "caps count" 2 (List.length decoded.capabilities)
  | Error _ -> fail "join request decode failed"

let test_join_response_make () =
  let jr = Masc_pb.Masc.V1.JoinResponse.make
    ~success:true
    ~message:"Welcome"
    () in
  check bool "success" true jr.success;
  check string "message" "Welcome" jr.message

let test_join_response_name () =
  let n = Masc_pb.Masc.V1.JoinResponse.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   LeaveRequest/Response Tests
   ============================================================ *)

let test_leave_request_make () =
  let lr = Masc_pb.Masc.V1.LeaveRequest.make
    ~agent_name:"claude-leaving"
    () in
  (* LeaveRequest is a string type wrapping agent_name *)
  check string "agent_name" "claude-leaving" lr

let test_leave_response_make () =
  let lr = Masc_pb.Masc.V1.LeaveResponse.make
    ~success:true
    ~message:"Goodbye"
    () in
  check bool "success" true lr.success;
  check string "message" "Goodbye" lr.message

(* ============================================================
   StatusRequest/Response Tests
   ============================================================ *)

let test_status_request_make () =
  let sr = Masc_pb.Masc.V1.StatusRequest.make () in
  (* StatusRequest is essentially empty or has minimal fields *)
  let _ = sr in ()

let test_status_response_make () =
  let agent = Masc_pb.Masc.V1.Agent.make ~name:"a1" ~status:"active" () in
  let task = Masc_pb.Masc.V1.Task.make ~id:"t1" ~title:"Task 1" () in
  let sr = Masc_pb.Masc.V1.StatusResponse.make
    ~agents:[agent]
    ~tasks:[task]
    ~message_count:10
    ~room_path:"/tmp/test"
    ~project_name:"test-project"
    () in
  check int "agents count" 1 (List.length sr.agents);
  check int "tasks count" 1 (List.length sr.tasks);
  check int "message_count" 10 sr.message_count;
  check string "room_path" "/tmp/test" sr.room_path;
  check string "project_name" "test-project" sr.project_name

let test_status_response_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.StatusResponse.make
    ~agents:[Masc_pb.Masc.V1.Agent.make ~name:"agent1" ()]
    ~tasks:[]
    ~message_count:5
    ~room_path:"/path"
    ~project_name:"proj"
    () in
  let writer = Masc_pb.Masc.V1.StatusResponse.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.StatusResponse.from_proto reader with
  | Ok decoded ->
    check int "message_count" 5 decoded.message_count;
    check string "project_name" "proj" decoded.project_name;
    check int "agents" 1 (List.length decoded.agents)
  | Error _ -> fail "status response decode failed"

(* ============================================================
   AddTaskRequest/Response Tests
   ============================================================ *)

let test_add_task_request_make () =
  let atr = Masc_pb.Masc.V1.AddTaskRequest.make
    ~title:"New task"
    ~description:"Do something"
    ~priority:2
    () in
  check string "title" "New task" atr.title;
  check string "description" "Do something" atr.description;
  check int "priority" 2 atr.priority

let test_add_task_response_make () =
  let atr = Masc_pb.Masc.V1.AddTaskResponse.make
    ~success:true
    ~task_id:"t-new"
    ~message:"Created"
    () in
  check bool "success" true atr.success;
  check string "task_id" "t-new" atr.task_id;
  check string "message" "Created" atr.message

(* ============================================================
   BroadcastResponse Tests
   ============================================================ *)

let test_broadcast_response_make () =
  let br = Masc_pb.Masc.V1.BroadcastResponse.make
    ~success:true
    ~seq:42
    () in
  check bool "success" true br.success;
  check int "seq" 42 br.seq

(* ============================================================
   PlanningContext Tests
   ============================================================ *)

let test_planning_context_make () =
  let pc = Masc_pb.Masc.V1.PlanningContext.make
    ~task_id:"task-sprint"
    ~task_plan:"Plan for next sprint"
    ~notes:["note1"; "note2"; "note3"]
    ~deliverable:"sprint-output"
    () in
  check string "task_id" "task-sprint" pc.task_id;
  check string "task_plan" "Plan for next sprint" pc.task_plan;
  check int "notes count" 3 (List.length pc.notes);
  check string "deliverable" "sprint-output" pc.deliverable

let test_planning_context_name () =
  let n = Masc_pb.Masc.V1.PlanningContext.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   JSON Roundtrip Tests
   ============================================================ *)

let json_opts = Ocaml_protoc_plugin.Json_options.default

let test_agent_json_roundtrip () =
  let original = Masc_pb.Masc.V1.Agent.make
    ~name:"json-agent"
    ~status:"idle"
    ~capabilities:["test"]
    () in
  let json = Masc_pb.Masc.V1.Agent.to_json json_opts original in
  match Masc_pb.Masc.V1.Agent.from_json json with
  | Ok decoded ->
    check string "name" original.name decoded.name;
    check string "status" original.status decoded.status
  | Error _ -> fail "agent json decode failed"

let test_task_json_roundtrip () =
  let original = Masc_pb.Masc.V1.Task.make
    ~id:"json-task"
    ~title:"JSON test"
    ~status:"done"
    ~priority:3
    () in
  let json = Masc_pb.Masc.V1.Task.to_json json_opts original in
  match Masc_pb.Masc.V1.Task.from_json json with
  | Ok decoded ->
    check string "id" original.id decoded.id;
    check string "title" original.title decoded.title
  | Error _ -> fail "task json decode failed"

let test_message_json_roundtrip () =
  let original = Masc_pb.Masc.V1.Message.make
    ~id:"json-msg"
    ~from:"test"
    ~content:"json content"
    ~seq:7
    () in
  let json = Masc_pb.Masc.V1.Message.to_json json_opts original in
  match Masc_pb.Masc.V1.Message.from_json json with
  | Ok decoded ->
    check string "id" original.id decoded.id;
    check int "seq" original.seq decoded.seq
  | Error _ -> fail "message json decode failed"

(* ============================================================
   ClaimTask Tests
   ============================================================ *)

let test_claim_task_request_make () =
  let r = Masc_pb.Masc.V1.ClaimTaskRequest.make
    ~agent_name:"claimer" ~task_id:"t-claim" () in
  check string "agent_name" "claimer" r.agent_name;
  check string "task_id" "t-claim" r.task_id

let test_claim_task_response_make () =
  let r = Masc_pb.Masc.V1.ClaimTaskResponse.make
    ~success:true ~message:"Claimed" () in
  check bool "success" true r.success;
  check string "message" "Claimed" r.message

let test_claim_task_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.ClaimTaskRequest.make
    ~agent_name:"agent-a" ~task_id:"t-100" () in
  let encoded = Masc_pb.Masc.V1.ClaimTaskRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.ClaimTaskRequest.from_proto reader with
  | Ok decoded -> check string "task_id" "t-100" decoded.task_id
  | Error _ -> fail "claim_task proto decode failed"

let test_claim_task_json_roundtrip () =
  let original = Masc_pb.Masc.V1.ClaimTaskResponse.make
    ~success:true ~message:"ok" () in
  let json = Masc_pb.Masc.V1.ClaimTaskResponse.to_json json_opts original in
  match Masc_pb.Masc.V1.ClaimTaskResponse.from_json json with
  | Ok decoded -> check bool "success" true decoded.success
  | Error _ -> fail "claim_task_response json decode failed"

(* ============================================================
   DoneTask Tests
   ============================================================ *)

let test_done_task_request_make () =
  let r = Masc_pb.Masc.V1.DoneTaskRequest.make
    ~agent_name:"worker" ~task_id:"t-done" ~notes:"All complete" () in
  check string "agent_name" "worker" r.agent_name;
  check string "notes" "All complete" r.notes

let test_done_task_response_make () =
  let r = Masc_pb.Masc.V1.DoneTaskResponse.make
    ~success:true ~message:"Marked done" () in
  check bool "success" true r.success

let test_done_task_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.DoneTaskRequest.make
    ~agent_name:"a" ~task_id:"t-1" ~notes:"n" () in
  let encoded = Masc_pb.Masc.V1.DoneTaskRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.DoneTaskRequest.from_proto reader with
  | Ok decoded -> check string "notes" "n" decoded.notes
  | Error _ -> fail "done_task proto decode failed"

(* ============================================================
   CancelTask Tests
   ============================================================ *)

let test_cancel_task_request_make () =
  let r = Masc_pb.Masc.V1.CancelTaskRequest.make
    ~agent_name:"canceller" ~task_id:"t-cancel" ~reason:"No longer needed" () in
  check string "reason" "No longer needed" r.reason

let test_cancel_task_response_make () =
  let r = Masc_pb.Masc.V1.CancelTaskResponse.make
    ~success:true ~message:"Cancelled" () in
  check bool "success" true r.success

let test_cancel_task_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.CancelTaskRequest.make
    ~agent_name:"a" ~task_id:"t" ~reason:"r" () in
  let encoded = Masc_pb.Masc.V1.CancelTaskRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.CancelTaskRequest.from_proto reader with
  | Ok decoded -> check string "reason" "r" decoded.reason
  | Error _ -> fail "cancel_task proto decode failed"

(* ============================================================
   GetMessages Tests
   ============================================================ *)

let test_get_messages_request_make () =
  let r = Masc_pb.Masc.V1.GetMessagesRequest.make
    ~since_seq:5 ~limit:20 () in
  check int "since_seq" 5 r.since_seq;
  check int "limit" 20 r.limit

let test_get_messages_response_make () =
  let msg1 = Masc_pb.Masc.V1.Message.make ~id:"m1" ~content:"hi" () in
  let resp = Masc_pb.Masc.V1.GetMessagesResponse.make ~messages:[msg1] () in
  check int "count" 1 (List.length resp)

let test_get_messages_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.GetMessagesRequest.make ~since_seq:10 ~limit:50 () in
  let encoded = Masc_pb.Masc.V1.GetMessagesRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.GetMessagesRequest.from_proto reader with
  | Ok decoded -> check int "limit" 50 decoded.limit
  | Error _ -> fail "get_messages proto decode failed"

(* ============================================================
   CreateVote Tests
   ============================================================ *)

let test_create_vote_request_make () =
  let r = Masc_pb.Masc.V1.CreateVoteRequest.make
    ~proposer:"claude" ~topic:"Best language"
    ~options:["OCaml"; "Rust"; "Haskell"] ~required_votes:3 () in
  check string "proposer" "claude" r.proposer;
  check int "options count" 3 (List.length r.options);
  check int "required_votes" 3 r.required_votes

let test_create_vote_response_make () =
  let r = Masc_pb.Masc.V1.CreateVoteResponse.make
    ~success:true ~vote_id:"v-001" () in
  check string "vote_id" "v-001" r.vote_id

let test_create_vote_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.CreateVoteRequest.make
    ~proposer:"p" ~topic:"t" ~options:["a";"b"] ~required_votes:2 () in
  let encoded = Masc_pb.Masc.V1.CreateVoteRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.CreateVoteRequest.from_proto reader with
  | Ok decoded -> check string "topic" "t" decoded.topic
  | Error _ -> fail "create_vote proto decode failed"

(* ============================================================
   CastVote Tests
   ============================================================ *)

let test_cast_vote_request_make () =
  let r = Masc_pb.Masc.V1.CastVoteRequest.make
    ~agent_name:"voter" ~vote_id:"v-001" ~choice:"OCaml" () in
  check string "choice" "OCaml" r.choice

let test_cast_vote_response_make () =
  let r = Masc_pb.Masc.V1.CastVoteResponse.make
    ~success:true ~message:"Vote cast" ~status:"open" ~result:"" () in
  check string "status" "open" r.status

let test_cast_vote_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.CastVoteRequest.make
    ~agent_name:"a" ~vote_id:"v" ~choice:"c" () in
  let encoded = Masc_pb.Masc.V1.CastVoteRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.CastVoteRequest.from_proto reader with
  | Ok decoded -> check string "choice" "c" decoded.choice
  | Error _ -> fail "cast_vote proto decode failed"

(* ============================================================
   InitPlan Tests
   ============================================================ *)

let test_init_plan_request_make () =
  let r = Masc_pb.Masc.V1.InitPlanRequest.make ~task_id:"plan-task" () in
  check string "task_id" "plan-task" r

let test_init_plan_response_make () =
  let r = Masc_pb.Masc.V1.InitPlanResponse.make ~success:true () in
  check bool "success" true r.success;
  check (option reject) "no context" None r.context

let test_init_plan_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.InitPlanRequest.make ~task_id:"t-plan" () in
  let encoded = Masc_pb.Masc.V1.InitPlanRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.InitPlanRequest.from_proto reader with
  | Ok decoded -> check string "task_id" "t-plan" decoded
  | Error _ -> fail "init_plan proto decode failed"

(* ============================================================
   UpdatePlan Tests
   ============================================================ *)

let test_update_plan_request_make () =
  let r = Masc_pb.Masc.V1.UpdatePlanRequest.make
    ~task_id:"t-upd" ~content:"New plan content" () in
  check string "task_id" "t-upd" r.task_id;
  check string "content" "New plan content" r.content

let test_update_plan_response_make () =
  let r = Masc_pb.Masc.V1.UpdatePlanResponse.make ~success:true () in
  check bool "success" true r.success

let test_update_plan_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.UpdatePlanRequest.make
    ~task_id:"t" ~content:"c" () in
  let encoded = Masc_pb.Masc.V1.UpdatePlanRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.UpdatePlanRequest.from_proto reader with
  | Ok decoded -> check string "content" "c" decoded.content
  | Error _ -> fail "update_plan proto decode failed"

(* ============================================================
   AddNote Tests
   ============================================================ *)

let test_add_note_request_make () =
  let r = Masc_pb.Masc.V1.AddNoteRequest.make
    ~task_id:"t-note" ~note:"Important note" () in
  check string "note" "Important note" r.note

let test_add_note_response_make () =
  let r = Masc_pb.Masc.V1.AddNoteResponse.make ~success:true () in
  check bool "success" true r.success

let test_add_note_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.AddNoteRequest.make
    ~task_id:"t" ~note:"note" () in
  let encoded = Masc_pb.Masc.V1.AddNoteRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.AddNoteRequest.from_proto reader with
  | Ok decoded -> check string "note" "note" decoded.note
  | Error _ -> fail "add_note proto decode failed"

(* ============================================================
   GetPlan Tests
   ============================================================ *)

let test_get_plan_request_make () =
  let r = Masc_pb.Masc.V1.GetPlanRequest.make ~task_id:"t-get" () in
  check string "task_id" "t-get" r

let test_get_plan_response_make () =
  let r = Masc_pb.Masc.V1.GetPlanResponse.make ~success:true () in
  check bool "success" true r.success

let test_get_plan_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.GetPlanRequest.make ~task_id:"t-gp" () in
  let encoded = Masc_pb.Masc.V1.GetPlanRequest.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.GetPlanRequest.from_proto reader with
  | Ok decoded -> check string "task_id" "t-gp" decoded
  | Error _ -> fail "get_plan proto decode failed"

(* ============================================================
   PlanningContext Proto/JSON Roundtrips
   ============================================================ *)

let test_planning_context_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.PlanningContext.make
    ~task_id:"ctx-t" ~task_plan:"plan" ~notes:["n1";"n2"]
    ~deliverable:"output" () in
  let encoded = Masc_pb.Masc.V1.PlanningContext.to_proto original in
  let reader = Ocaml_protoc_plugin.Reader.create (Ocaml_protoc_plugin.Writer.contents encoded) in
  match Masc_pb.Masc.V1.PlanningContext.from_proto reader with
  | Ok decoded ->
    check string "task_id" "ctx-t" decoded.task_id;
    check int "notes" 2 (List.length decoded.notes)
  | Error _ -> fail "planning_context proto decode failed"

let test_planning_context_json_roundtrip () =
  let original = Masc_pb.Masc.V1.PlanningContext.make
    ~task_id:"jctx" ~task_plan:"jp" ~deliverable:"jd" () in
  let json = Masc_pb.Masc.V1.PlanningContext.to_json json_opts original in
  match Masc_pb.Masc.V1.PlanningContext.from_json json with
  | Ok decoded -> check string "task_id" "jctx" decoded.task_id
  | Error _ -> fail "planning_context json decode failed"

(* ============================================================
   Additional JSON Roundtrips
   ============================================================ *)

let test_vote_json_roundtrip () =
  let original = Masc_pb.Masc.V1.Vote.make
    ~id:"v-j" ~proposer:"p" ~topic:"t" ~options:["a";"b"] () in
  let json = Masc_pb.Masc.V1.Vote.to_json json_opts original in
  match Masc_pb.Masc.V1.Vote.from_json json with
  | Ok decoded -> check string "id" "v-j" decoded.id
  | Error _ -> fail "vote json decode failed"

let test_broadcast_request_json_roundtrip () =
  let original = Masc_pb.Masc.V1.BroadcastRequest.make
    ~agent_name:"br-agent" ~message:"broadcast msg" () in
  let json = Masc_pb.Masc.V1.BroadcastRequest.to_json json_opts original in
  match Masc_pb.Masc.V1.BroadcastRequest.from_json json with
  | Ok decoded -> check string "message" "broadcast msg" decoded.message
  | Error _ -> fail "broadcast_request json decode failed"

let test_status_response_json_roundtrip () =
  let agent = Masc_pb.Masc.V1.Agent.make ~name:"a1" ~status:"active" () in
  let original = Masc_pb.Masc.V1.StatusResponse.make ~agents:[agent] () in
  let json = Masc_pb.Masc.V1.StatusResponse.to_json json_opts original in
  match Masc_pb.Masc.V1.StatusResponse.from_json json with
  | Ok decoded -> check int "agents count" 1 (List.length decoded.agents)
  | Error _ -> fail "status_response json decode failed"

(* ============================================================
   Test Runners
   ============================================================ *)

let () =
  run "MASC Protobuf Coverage" [
    "empty", [
      test_case "make" `Quick test_empty_make;
      test_case "name" `Quick test_empty_name;
    ];
    "agent", [
      test_case "make default" `Quick test_agent_make_default;
      test_case "make with values" `Quick test_agent_make_with_values;
      test_case "name" `Quick test_agent_name;
      test_case "merge" `Quick test_agent_merge;
    ];
    "task", [
      test_case "make default" `Quick test_task_make_default;
      test_case "make with values" `Quick test_task_make_with_values;
      test_case "name" `Quick test_task_name;
    ];
    "broadcast_request", [
      test_case "make" `Quick test_broadcast_request_make;
      test_case "name" `Quick test_broadcast_request_name;
    ];
    "message", [
      test_case "make default" `Quick test_message_make_default;
      test_case "make with values" `Quick test_message_make_with_values;
      test_case "name" `Quick test_message_name;
      test_case "merge" `Quick test_message_merge;
    ];
    "vote", [
      test_case "make default" `Quick test_vote_make_default;
      test_case "make with values" `Quick test_vote_make_with_values;
      test_case "name" `Quick test_vote_name;
    ];
    "join", [
      test_case "request make" `Quick test_join_request_make;
      test_case "request name" `Quick test_join_request_name;
      test_case "response make" `Quick test_join_response_make;
      test_case "response name" `Quick test_join_response_name;
    ];
    "leave", [
      test_case "request make" `Quick test_leave_request_make;
      test_case "response make" `Quick test_leave_response_make;
    ];
    "status", [
      test_case "request make" `Quick test_status_request_make;
      test_case "response make" `Quick test_status_response_make;
    ];
    "add_task", [
      test_case "request make" `Quick test_add_task_request_make;
      test_case "response make" `Quick test_add_task_response_make;
    ];
    "claim_task", [
      test_case "request make" `Quick test_claim_task_request_make;
      test_case "response make" `Quick test_claim_task_response_make;
      test_case "proto roundtrip" `Quick test_claim_task_proto_roundtrip;
      test_case "json roundtrip" `Quick test_claim_task_json_roundtrip;
    ];
    "done_task", [
      test_case "request make" `Quick test_done_task_request_make;
      test_case "response make" `Quick test_done_task_response_make;
      test_case "proto roundtrip" `Quick test_done_task_proto_roundtrip;
    ];
    "cancel_task", [
      test_case "request make" `Quick test_cancel_task_request_make;
      test_case "response make" `Quick test_cancel_task_response_make;
      test_case "proto roundtrip" `Quick test_cancel_task_proto_roundtrip;
    ];
    "get_messages", [
      test_case "request make" `Quick test_get_messages_request_make;
      test_case "response make" `Quick test_get_messages_response_make;
      test_case "proto roundtrip" `Quick test_get_messages_proto_roundtrip;
    ];
    "create_vote", [
      test_case "request make" `Quick test_create_vote_request_make;
      test_case "response make" `Quick test_create_vote_response_make;
      test_case "proto roundtrip" `Quick test_create_vote_proto_roundtrip;
    ];
    "cast_vote", [
      test_case "request make" `Quick test_cast_vote_request_make;
      test_case "response make" `Quick test_cast_vote_response_make;
      test_case "proto roundtrip" `Quick test_cast_vote_proto_roundtrip;
    ];
    "init_plan", [
      test_case "request make" `Quick test_init_plan_request_make;
      test_case "response make" `Quick test_init_plan_response_make;
      test_case "proto roundtrip" `Quick test_init_plan_proto_roundtrip;
    ];
    "update_plan", [
      test_case "request make" `Quick test_update_plan_request_make;
      test_case "response make" `Quick test_update_plan_response_make;
      test_case "proto roundtrip" `Quick test_update_plan_proto_roundtrip;
    ];
    "add_note", [
      test_case "request make" `Quick test_add_note_request_make;
      test_case "response make" `Quick test_add_note_response_make;
      test_case "proto roundtrip" `Quick test_add_note_proto_roundtrip;
    ];
    "get_plan", [
      test_case "request make" `Quick test_get_plan_request_make;
      test_case "response make" `Quick test_get_plan_response_make;
      test_case "proto roundtrip" `Quick test_get_plan_proto_roundtrip;
    ];
    "broadcast_response", [
      test_case "make" `Quick test_broadcast_response_make;
    ];
    "planning_context", [
      test_case "make" `Quick test_planning_context_make;
      test_case "name" `Quick test_planning_context_name;
      test_case "proto roundtrip" `Quick test_planning_context_proto_roundtrip;
      test_case "json roundtrip" `Quick test_planning_context_json_roundtrip;
    ];
    "proto_roundtrip", [
      test_case "agent" `Quick test_agent_proto_roundtrip;
      test_case "task" `Quick test_task_proto_roundtrip;
      test_case "message" `Quick test_message_proto_roundtrip;
      test_case "vote" `Quick test_vote_proto_roundtrip;
      test_case "join_request" `Quick test_join_request_proto_roundtrip;
      test_case "status_response" `Quick test_status_response_proto_roundtrip;
    ];
    "json_roundtrip", [
      test_case "agent" `Quick test_agent_json_roundtrip;
      test_case "task" `Quick test_task_json_roundtrip;
      test_case "message" `Quick test_message_json_roundtrip;
      test_case "vote" `Quick test_vote_json_roundtrip;
      test_case "broadcast_request" `Quick test_broadcast_request_json_roundtrip;
      test_case "status_response" `Quick test_status_response_json_roundtrip;
    ];
  ]
