(* The diagram is generated by asking the FSM, so most of what could go wrong
   is not "the picture disagrees with the machine" -- it cannot -- but the
   generator dropping states, inventing nodes, or folding away a distinction
   the machine makes. Each test below plants one of those. *)

open Alcotest

let diagram () = Turn_fsm_mermaid.diagram ()

let contains haystack needle =
  let nl = String.length needle and hl = String.length haystack in
  let rec go i = i + nl <= hl && (String.sub haystack i nl = needle || go (i + 1)) in
  nl = 0 || go 0

let lines s = String.split_on_char '\n' s |> List.filter (fun l -> l <> "")

(* [all_states] is written out by hand -- the deriver works on the plain
   mirror type, not the GADT -- so it is the one place a new state could be
   forgotten. [all_symbols] is derived, so comparing against it turns that
   omission into a red test instead of a diagram quietly missing a box. *)
let test_every_state_is_enumerated () =
  let from_states =
    List.sort_uniq String.compare
      (List.map Turn_fsm.any_state_symbol Turn_fsm.all_states)
  in
  let derived = List.sort_uniq String.compare Turn_fsm.all_symbols in
  check (list string) "all_states covers every derived symbol" derived from_states

(* Both carry a reason and the FSM branches on it. One representative each
   would still typecheck and still produce a plausible diagram, just one
   missing most of its failure edges. *)
let test_every_reason_is_enumerated () =
  check int "every failure reason" 6 (List.length Turn_fsm.all_failure_reasons);
  check int "every cancel reason" 6 (List.length Turn_fsm.all_cancel_reasons);
  let routing_failures =
    List.filter
      (fun (f, t, _) -> f = "runtime_routing" && t = "failed")
      (Turn_fsm_mermaid.edges ())
  in
  (* Four distinct actions reach [failed] from routing. Sampling one reason
     would leave one. *)
  check int "routing reaches failed by four named actions" 4
    (List.length routing_failures)

(* Every line the generator draws has to be an edge the FSM admits, asked
   again here rather than trusted. *)
let test_no_edge_the_fsm_refuses () =
  let admitted =
    List.concat_map
      (fun from_any ->
        List.filter_map
          (fun to_any ->
            let (Turn_fsm.Any from_state) = from_any in
            let (Turn_fsm.Any to_state) = to_any in
            match Turn_fsm.classify_transition ~from_state ~to_state () with
            | None -> None
            | Some action ->
                Some
                  ( Turn_fsm.to_tla_symbol from_state,
                    Turn_fsm.to_tla_symbol to_state,
                    Turn_fsm.transition_action_label action ))
          Turn_fsm.all_states)
      Turn_fsm.all_states
  in
  List.iter
    (fun edge ->
      check bool "drawn edge is one the FSM admits" true (List.mem edge admitted))
    (Turn_fsm_mermaid.edges ());
  List.iter
    (fun edge ->
      check bool "admitted edge is drawn" true
        (List.mem edge (Turn_fsm_mermaid.edges ())))
    admitted

(* Folding on (from, to, action) is only safe if it never merges two lines
   that meant different things. It merges six GenericFail reasons into one and
   must not merge ProviderError into it. *)
let test_folding_keeps_distinct_actions () =
  let streaming_failed =
    List.filter_map
      (fun (f, t, a) -> if f = "streaming" && t = "failed" then Some a else None)
      (Turn_fsm_mermaid.edges ())
  in
  let sorted = List.sort_uniq String.compare streaming_failed in
  check (list string) "streaming reaches failed three named ways"
    [ "GenericFail"; "ProviderError"; "ReceiptLost" ] sorted;
  check int "no duplicate lines survive the fold"
    (List.length sorted) (List.length streaming_failed)

(* The entry arrow used to name "Idle" while the symbols are lowercase, which
   drew a second empty node for a state that does not exist. Every node any
   line mentions has to be one the FSM reports. *)
let test_no_invented_nodes () =
  let known = Turn_fsm_mermaid.node_symbols () in
  List.iter
    (fun line ->
      let line = String.trim line in
      match String.index_opt line '>' with
      | None -> ()
      | Some _ ->
          List.iter
            (fun (f, t, _) ->
              check bool ("left node exists: " ^ f) true (List.mem f known);
              check bool ("right node exists: " ^ t) true (List.mem t known))
            (Turn_fsm_mermaid.edges ()))
    (lines (diagram ()));
  let d = diagram () in
  List.iter
    (fun sym ->
      check bool ("entry arrow names a real idle symbol: " ^ sym) true
        (contains d ("[*] --> " ^ sym)))
    Turn_fsm.idle_symbols

(* A caller holding the constructor spelling must still light a node. An exact
   match highlighted nothing and gave no sign it had failed. *)
let test_current_highlight_ignores_case () =
  check bool "constructor spelling highlights" true
    (contains (Turn_fsm_mermaid.diagram ~current:"Streaming" ())
       "class streaming current");
  check bool "symbol spelling highlights" true
    (contains (Turn_fsm_mermaid.diagram ~current:"streaming" ())
       "class streaming current");
  (* A name that is not a state adds nothing rather than a node for itself. *)
  let bogus = Turn_fsm_mermaid.diagram ~current:"Reticulating" () in
  check bool "an unknown state highlights nothing" false
    (contains bogus "current\n" && contains bogus "Reticulating");
  check bool "and invents no node" false (contains bogus "Reticulating")

let test_terminals_reach_the_end () =
  let d = diagram () in
  List.iter
    (fun sym ->
      check bool (sym ^ " reaches the end marker") true
        (contains d (sym ^ " --> [*]")))
    Turn_fsm.terminal_symbols

let () =
  run "turn_fsm_mermaid"
    [
      ( "derivation",
        [
          test_case "every state enumerated" `Quick test_every_state_is_enumerated;
          test_case "every reason enumerated" `Quick test_every_reason_is_enumerated;
          test_case "no edge the FSM refuses" `Quick test_no_edge_the_fsm_refuses;
        ] );
      ( "rendering",
        [
          test_case "folding keeps distinct actions" `Quick
            test_folding_keeps_distinct_actions;
          test_case "no invented nodes" `Quick test_no_invented_nodes;
          test_case "current highlight ignores case" `Quick
            test_current_highlight_ignores_case;
          test_case "terminals reach the end" `Quick test_terminals_reach_the_end;
        ] );
    ]
