module Types = Masc_domain

(* Generates test_mcp_tool_matrix_names_gen.ml from runtime tool registry.
   Run via dune rule — do not edit the generated file manually. *)

let sorted_unique_strings lst =
  List.sort_uniq String.compare lst

let () =
  let names =
    Masc_mcp.Config.raw_all_tool_schemas
    |> List.map (fun (schema : Masc_domain.tool_schema) -> schema.name)
    |> sorted_unique_strings
  in
  Printf.printf
    "(* AUTO-GENERATED by tool_inventory_gen.ml — do not edit *)\n\n";
  Printf.printf "let names =\n  [\n";
  List.iter (fun name -> Printf.printf "    %S;\n" name) names;
  Printf.printf "  ]\n"
