import re
with open("lib/tool_agent.ml", "r") as f: content = f.read()
content = re.sub(r'let handle_agent_card ctx args =.*?\)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let handle_collaboration_graph ctx args =.*?\)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'type agent_card_action =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let agent_card_action_to_string =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let agent_card_action_of_string_opt =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let all_agent_card_actions =.*?\n', '', content, flags=re.DOTALL)
content = re.sub(r'let valid_agent_card_action_strings =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'type collaboration_format =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let collaboration_format_to_string =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let collaboration_format_of_string_opt =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let all_collaboration_formats =.*?\n', '', content, flags=re.DOTALL)
content = re.sub(r'let valid_collaboration_format_strings =.*?\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'\| "masc_agent_card" -> Some \(handle_agent_card ctx args\)\n', '', content)
content = re.sub(r'\| "masc_collaboration_graph" -> Some \(handle_collaboration_graph ctx args\)\n', '', content)
with open("lib/tool_agent.ml", "w") as f: f.write(content)
print("done")
