import re
with open("test/test_tool_agent_coverage.ml", "r") as f: content = f.read()
content = re.sub(r'let test_handle_collaboration_graph_text.*?Alcotest\.\(check bool\) "has response" true \(String\.length msg > 0\);\n  \)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let test_handle_collaboration_graph_json.*?Alcotest\.\(check bool\) "returns JSON" true \(String\.contains msg \'{\' \);\n  \)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let test_handle_agent_card_get.*?Alcotest\.\(check bool\) "returns JSON" true \(String\.contains msg \'{\' \);\n  \)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'let test_handle_agent_card_refresh.*?Alcotest\.\(check bool\) "has response" true \(String\.length msg > 0\);\n  \)\n\n', '', content, flags=re.DOTALL)
content = re.sub(r'\("collaboration_graph", \[.*?\]\);', '', content, flags=re.DOTALL)
content = re.sub(r'\("agent_card", \[.*?\]\);', '', content, flags=re.DOTALL)
with open("test/test_tool_agent_coverage.ml", "w") as f: f.write(content)
print("done")
