type deps = Server_command_plane_http_support.deps = {
  query_param : Httpun.Request.t -> string -> string option;
  int_query_param : Httpun.Request.t -> string -> default:int -> int;
  operator_actor_hint : Httpun.Request.t -> string option;
  get_session_id_any : Httpun.Request.t -> string option;
  auth_token_from_request : Httpun.Request.t -> string option;
  get_switch : unit -> Eio.Switch.t;
  get_clock : unit -> float Eio.Time.clock_ty Eio.Resource.t;
  get_net : unit -> [ `Generic | `Unix ] Eio.Net.ty Eio.Resource.t;
  get_origin : Httpun.Request.t -> string;
  cors_headers : string -> (string * string) list;
}

let command_plane_summary_http_json = Server_command_plane_http_support.command_plane_summary_http_json
let command_plane_snapshot_http_json = Server_command_plane_http_support.command_plane_snapshot_http_json
let command_plane_topology_http_json = Server_command_plane_http_support.command_plane_topology_http_json
let command_plane_units_http_json = Server_command_plane_http_support.command_plane_units_http_json
let command_plane_operations_http_json = Server_command_plane_http_support.command_plane_operations_http_json
let command_plane_detachments_http_json = Server_command_plane_http_support.command_plane_detachments_http_json
let command_plane_detachment_status_http_json = Server_command_plane_http_support.command_plane_detachment_status_http_json
let command_plane_decisions_http_json = Server_command_plane_http_support.command_plane_decisions_http_json
let command_plane_capacity_http_json = Server_command_plane_http_support.command_plane_capacity_http_json
let command_plane_alerts_http_json = Server_command_plane_http_support.command_plane_alerts_http_json
let command_plane_traces_http_json = Server_command_plane_http_support.command_plane_traces_http_json
let command_plane_swarm_http_json = Server_command_plane_http_support.command_plane_swarm_http_json
let command_plane_orchestra_http_json = Server_command_plane_http_support.command_plane_orchestra_http_json
let command_plane_unit_define_http_json = Server_command_plane_http_support.command_plane_unit_define_http_json
let command_plane_operation_start_http_json = Server_command_plane_http_support.command_plane_operation_start_http_json
let command_plane_operation_checkpoint_http_json = Server_command_plane_http_mutations.command_plane_operation_checkpoint_http_json
let command_plane_unit_reparent_http_json = Server_command_plane_http_mutations.command_plane_unit_reparent_http_json
let command_plane_unit_reassign_http_json = Server_command_plane_http_mutations.command_plane_unit_reassign_http_json
let command_plane_operation_pause_http_json = Server_command_plane_http_mutations.command_plane_operation_pause_http_json
let command_plane_operation_resume_http_json = Server_command_plane_http_mutations.command_plane_operation_resume_http_json
let command_plane_operation_stop_http_json = Server_command_plane_http_mutations.command_plane_operation_stop_http_json
let command_plane_operation_finalize_http_json = Server_command_plane_http_mutations.command_plane_operation_finalize_http_json
let command_plane_dispatch_plan_http_json = Server_command_plane_http_mutations.command_plane_dispatch_plan_http_json
let command_plane_dispatch_assign_http_json = Server_command_plane_http_mutations.command_plane_dispatch_assign_http_json
let command_plane_dispatch_rebalance_http_json = Server_command_plane_http_mutations.command_plane_dispatch_rebalance_http_json
let command_plane_dispatch_escalate_http_json = Server_command_plane_http_mutations.command_plane_dispatch_escalate_http_json
let command_plane_dispatch_recall_http_json = Server_command_plane_http_mutations.command_plane_dispatch_recall_http_json
let command_plane_dispatch_tick_http_json = Server_command_plane_http_mutations.command_plane_dispatch_tick_http_json
let command_plane_policy_status_http_json = Server_command_plane_http_mutations.command_plane_policy_status_http_json
let command_plane_policy_approve_http_json = Server_command_plane_http_mutations.command_plane_policy_approve_http_json
let command_plane_policy_deny_http_json = Server_command_plane_http_mutations.command_plane_policy_deny_http_json
let command_plane_policy_update_http_json = Server_command_plane_http_mutations.command_plane_policy_update_http_json
let command_plane_policy_freeze_http_json = Server_command_plane_http_mutations.command_plane_policy_freeze_http_json
let command_plane_policy_kill_switch_http_json = Server_command_plane_http_mutations.command_plane_policy_kill_switch_http_json
let command_plane_help_http_json = Server_command_plane_http_help.command_plane_help_http_json
let command_plane_error_json = Server_command_plane_http_help.command_plane_error_json
