val metric_keeper_turns : string
val metric_keeper_input_tokens : string
val metric_keeper_output_tokens : string
val metric_keeper_cache_creation_tokens : string
val metric_keeper_cache_read_tokens : string
val metric_keeper_usage_anomalies : string
val metric_keeper_total_cost_usd : string
val metric_keeper_turn_scheduled : string
val metric_keeper_turn_completed : string
val metric_keeper_idle_seconds : string
val metric_keeper_contract_violations : string
val metric_keeper_alive_but_stuck : string
val metric_keeper_alive_but_stuck_seconds : string
val metric_keeper_alive_but_stuck_threshold_seconds : string
val metric_keeper_alive_but_stuck_recovery_requests : string
val metric_keeper_alive_but_stuck_recovery : string
val metric_keeper_metric_emit_dropped : string
val metric_keeper_context_max_observed : string
val metric_keeper_turn_starts : string
val metric_keeper_turn_reattempts : string
val metric_keeper_turn_regressions : string
val metric_keeper_turn_livelock_blocks : string
val metric_keeper_turn_livelock_blocks_repeated : string
val metric_keeper_turn_livelock_blocks_threshold_park : string
val metric_keeper_turn_latency_bucket : string
val metric_keeper_turn_latency_by_model_bucket : string
val metric_keeper_provider_cooldown_skip : string
val metric_keeper_provider_cooldown_remaining_sec : string
val metric_keeper_provider_block_duration_sec : string
val metric_keeper_turn_queue_depth : string
val metric_keeper_supervisor_sweep_starts : string
val metric_keeper_supervisor_last_sweep_unixtime : string
