(** Receipt outcome classification. Matches the TLA+ spec
    [ReceiptOutcomeSet = {"receipt_unset", "receipt_skipped",
    "receipt_done", "receipt_failed", "receipt_cancelled"}] modulo the
    [receipt_unset] variant which is the initial-state-only marker and
    so cannot appear on a terminal receipt. The four terminal variants
    here cover every reachable outcome of a finished turn. See
    [specs/keeper-turn-fsm/KeeperTurnFSM.tla] invariants
    [EveryTurnHasTerminalReceipt] and [ReceiptMatchesState], and
    [specs/keeper-state-machine/KeeperOutcomesConservation.tla].
    [`Skipped] is generated by the [PhaseGateSkip] action: the turn
    reached terminal [Done] without dispatching to a provider, so it is
    a successful no-op rather than a failure or cancellation. *)
type outcome_kind = [ `Ok | `Skipped | `Error | `Cancelled ]

val outcome_kind_to_string : outcome_kind -> string
(** Stable serialisation: [`Ok -> "ok"], [`Skipped -> "skipped"],
    [`Error -> "error"], [`Cancelled -> "cancelled"]. Used at the JSON
    boundary while the receipt record still stores the legacy string
    form. *)

val outcome_kind_to_tla_receipt : outcome_kind -> string
(** TLA+ receipt symbol mapping: [`Ok] serializes as ["ok"] in JSON but
    corresponds to ["receipt_done"] in [KeeperTurnFSM.tla]; [`Error]
    similarly maps to ["receipt_failed"]. *)

val outcome_kind_of_string : string -> outcome_kind option
(** Parse the legacy string form. Recognises the four terminal kinds
    and returns [None] for everything else (including ["unset"]) so
    callers can decide whether to fail-closed or surface as [`Error]. *)

val outcome_kind_is_terminal_success : outcome_kind -> bool
(** [true] for [`Ok] and [`Skipped] (PhaseGateSkip is a successful
    no-op, not a failure). [false] for [`Error] and [`Cancelled].
    Used by dashboard "healthy" classification and action_radius
    success accounting. *)

type error_kind = private Error_kind of string

val error_kind_of_string : string -> error_kind
val error_kind_to_string : error_kind -> string

type cascade_name = Keeper_cascade_profile.runtime_name
(** Runtime cascade profile name as stored by execution receipts. Dynamic
    catalog names stay possible, but receipt construction must cross this
    typed boundary before persistence. *)

val cascade_name_of_string : string -> cascade_name
val cascade_name_to_string : cascade_name -> string

type receipt_authority_violation = {
  outcome : string;
  turn_state : string;
}
(** Witness of a [ReceiptIsAuthoritative] invariant violation.
    [outcome] holds the receipt-side string (e.g. ["receipt_done"]);
    [turn_state] is the offending turn-state symbol the caller
    presented. *)

val assert_receipt_authoritative :
  outcome:outcome_kind ->
  turn_state:string ->
  (unit, receipt_authority_violation) result
(** Runtime check for the TLA+ [ReceiptIsAuthoritative] invariant
    (specs/keeper-turn-fsm/KeeperTurnFSM.tla:336):
    [receipt_outcome = "receipt_done" => turn_state = "done"].

    Per [ReceiptMatchesState] the [Done] state also accepts
    [receipt_skipped] (PhaseGateSkip path), so this helper enforces
    the receipt-authoritative direction for both [`Ok] and [`Skipped]:
    a successful-terminal receipt MUST be paired with [turn_state =
    "done"]. [`Error] and [`Cancelled] are accepted here without
    further check; pairing them with the right turn_state is the
    responsibility of [ReceiptMatchesState] (a separate invariant).

    [turn_state] is the canonical TLA+ symbol form (e.g. [done],
    [failed], [cancelled], ...). Callers that hold a
    [Keeper_turn_fsm.turn_state] should pass
    [Keeper_turn_fsm.to_tla_symbol s].

    Returns [Error _] (never raises) so the caller can choose to
    fail-closed via [Result.Error] propagation or surface a metric.
    Memory: feedback_keeper_runtime_fail_closed_for_unknown_permissive_default. *)

type tool_surface =
  { turn_lane : string
  ; tool_surface_class : string
  ; tool_requirement : string
  ; visible_tool_count : int
  ; tool_gate_enabled : bool
  ; tool_surface_fallback_used : bool
  ; required_tools : string list
  ; missing_required_tools : string list
  }

type cascade_rotation_attempt =
  { from_cascade : cascade_name
  ; to_cascade : cascade_name
  ; reason : string
  ; outcome : string
  ; error_kind : error_kind option
  ; error_message : string option
  ; recorded_at : string
  }

type t =
  { keeper_name : string
  ; agent_name : string
  ; trace_id : string
  ; generation : int
  ; turn_count : int option
  ; current_task_id : string option
  ; goal_ids : string list
  ; outcome : string
  ; terminal_reason_code : string
  ; response_text_present : bool
  ; model_used : string option
  ; requested_tools : string list
  ; reported_tools : string list
  ; observed_tools : string list
  ; canonical_tools : string list
  ; unexpected_tools : string list
  ; tools_used : string list
  ; tool_contract_result : string
  ; tool_surface : tool_surface
  ; sandbox_kind : string
  ; sandbox_root : string option
  ; network_mode : string
  ; approval_profile : string option
  ; approval_profile_derived : bool
  ; cascade_name : cascade_name
  ; cascade_selected_model : string option
  ; cascade_attempt_count : int
  ; cascade_fallback_applied : bool
  ; cascade_outcome : string
  ; degraded_retry_applied : bool
  ; degraded_retry_cascade : cascade_name option
  ; fallback_reason : string option
  ; cascade_rotation_attempts : cascade_rotation_attempt list
  ; stop_reason : string option
  ; error_kind : error_kind option
  ; error_message : string option
  ; started_at : string
  ; ended_at : string
  }

val stop_reason_to_string : Oas_worker.stop_reason -> string
val sandbox_kind_of_meta : Keeper_types.keeper_meta -> string
val to_json : t -> Yojson.Safe.t

(** Derived display pair (disposition, reason) computed from receipt fields.
    Exposed for test access; the runtime path consumes it via [append]. *)
val operator_disposition : t -> string * string

(** [needs_operator_broadcast disposition] returns true when the disposition
    indicates a silent dead-end that operators must be notified about. *)
val needs_operator_broadcast : string -> bool

val operator_broadcast_payload :
  t -> disposition:string -> reason:string -> Yojson.Safe.t
(** Structured payload emitted for [keeper.operator_broadcast_required].
    Exposed so tests can pin the diagnostic fields operators need when a
    keeper turn pauses or stalls silently. *)

val append : Coord.config -> t -> unit
val latest_json : Coord.config -> string -> Yojson.Safe.t option
val latest_json_by_keeper :
  Coord.config -> string list -> (string * Yojson.Safe.t) list

(** Emit a watchdog-sourced operator_broadcast_required event for a keeper
    that has been Running but not produced a turn within the stale
    threshold. Used by the supervisor watchdog fiber (Step 3 of the
    keeper-pause-broadcast-watchdog change) to convert silent stalls into
    addressable events. *)
val emit_stale_keeper_broadcast :
  Coord.config ->
  keeper_name:string ->
  agent_name:string ->
  cascade_name:cascade_name ->
  trace_id:string ->
  generation:int ->
  stale_seconds:float ->
  last_turn_ts:float ->
  unit
