(** Receipt outcome classification. Matches the TLA+ spec
    [ReceiptOutcomeSet = {"receipt_unset", "receipt_skipped",
    "receipt_done", "receipt_failed", "receipt_cancelled"}] modulo the
    [receipt_unset] variant which is the initial-state-only marker and
    so cannot appear on a terminal receipt. The four terminal variants
    here cover every reachable outcome of a finished turn. See
    [specs/keeper-turn-fsm/KeeperTurnFSM.tla] invariants
    [EveryTurnHasTerminalReceipt] and [ReceiptMatchesState], and
    [specs/keeper-state-machine/KeeperOutcomesConservation.tla].
    [`Skipped] is generated by the [PhaseGateSkip] action: the turn
    reached terminal [Done] without dispatching to a provider, so it is
    a successful no-op rather than a failure or cancellation. *)
type outcome_kind =
  [ `Ok
  | `Skipped
  | `Error
  | `Cancelled
  ]

(** Stable serialisation: [`Ok -> "ok"], [`Skipped -> "skipped"],
    [`Error -> "error"], [`Cancelled -> "cancelled"]. *)
val outcome_kind_to_string : outcome_kind -> string

(** TLA+ receipt symbol mapping: [`Ok] serializes as ["ok"] in JSON but
    corresponds to ["receipt_done"] in [KeeperTurnFSM.tla]; [`Error]
    similarly maps to ["receipt_failed"]. *)
val outcome_kind_to_tla_receipt : outcome_kind -> string

type error_kind = private Error_kind of string

val error_kind_of_string : string -> error_kind
val error_kind_to_string : error_kind -> string

(** Witness of a [ReceiptIsAuthoritative] invariant violation.
    [outcome] holds the receipt-side string (e.g. ["receipt_done"]);
    [turn_state] is the offending turn-state symbol the caller
    presented. *)
type receipt_authority_violation =
  { outcome : string
  ; turn_state : string
  }

(** Runtime check for the TLA+ [ReceiptIsAuthoritative] invariant
    (specs/keeper-turn-fsm/KeeperTurnFSM.tla:336):
    [receipt_outcome = "receipt_done" => turn_state = "done"].

    Per [ReceiptMatchesState] the [Done] state also accepts
    [receipt_skipped] (PhaseGateSkip path), so this helper enforces
    the receipt-authoritative direction for both [`Ok] and [`Skipped]:
    a successful-terminal receipt MUST be paired with [turn_state =
    "done"]. [`Error] and [`Cancelled] are accepted here without
    further check; pairing them with the right turn_state is the
    responsibility of [ReceiptMatchesState] (a separate invariant).

    [turn_state] is the canonical TLA+ symbol form (e.g. [done],
    [failed], [cancelled], ...). Callers that hold a
    [Keeper_turn_fsm.turn_state] should pass
    [Keeper_turn_fsm.to_tla_symbol s].

    Returns [Error _] (never raises) so the caller can choose to
    fail-closed via [Result.Error] propagation or surface a metric.
    Memory: feedback_keeper_runtime_fail_closed_for_unknown_permissive_default. *)
val assert_receipt_authoritative
  :  outcome:outcome_kind
  -> turn_state:string
  -> (unit, receipt_authority_violation) result

type tool_surface =
  { turn_lane : Keeper_agent_tool_surface.turn_lane }

(** Receipt-level summary of how the in-turn runtime attempt sequence
    ended. Closed set; wire form is [runtime_outcome_to_string]. *)
type runtime_outcome =
  | Runtime_passed_to_next_model
  | Runtime_completed
  | Runtime_failed
  | Runtime_not_observed
  | Runtime_not_dispatched

val runtime_outcome_to_string : runtime_outcome -> string

(** Receipt-level observation of visible completion evidence. This field is
    telemetry only and cannot affect failure, lifecycle, authorization, or
    operator disposition. *)
type completion_contract_result =
  | Completion_observation_unknown
  | Completion_not_dispatched
  | Completion_no_visible_output
  | Completion_response_observed
  | Completion_tool_execution_observed

val completion_contract_result_to_string : completion_contract_result -> string

type t =
  { keeper_name : string
  ; trace_id : string
  ; turn_count : int option
      (** Absolute Keeper turn identity, shared with runtime manifest rows. *)
  ; agent_core_turn_count : int option
      (** Internal agent loop iterations within this Keeper turn. *)
  ; current_task_id : string option
  ; outcome : outcome_kind
  ; terminal_reason_code : string
  ; response_text_present : bool
  ; completion_contract_result : completion_contract_result
  ; actionable_signal : Keeper_contract_classifier.actionable_signal option
    (** World-observation signal captured at turn time. It is independent of
        completion evidence and does not authorize or block the turn. *)
  ; tool_surface : tool_surface
  ; sandbox_kind : Keeper_types_profile_sandbox.sandbox_profile
  ; sandbox_root : string option
  ; network_mode : Keeper_types_profile_sandbox.network_mode
  ; runtime_id : string
  ; runtime_selected_model : string option
  ; runtime_attempt_count : int
  ; runtime_lane_attempt_count : int
  ; runtime_fallback_applied : bool
  ; runtime_outcome : runtime_outcome
  ; agent_core_internal_runtime_allowed : bool
  ; degraded_retry_applied : Keeper_error_classify.degraded_retry option
    (** The lane an earlier turn deferred to and that this turn dispatched on.
        Empty when no lane was deferred, when this turn started somewhere
        else, or when it never reached a provider. *)
  ; degraded_retry_deferred : Keeper_error_classify.degraded_retry option
    (** The lane this turn leaves for a later turn. Independent of the field
        above: a turn can take up a deferred lane, fail there, and defer
        again, and both facts belong on its receipt. *)
  ; stop_reason : Runtime_agent.stop_reason option
  ; error_kind : error_kind option
  ; error_message : string option
  ; started_at : string
  ; ended_at : string
  ; extra_system_context_digest : string option
  ; extra_system_context_injected_size : int option
  ; extra_system_context_computed_size : int option
  }

val stop_reason_to_string : Runtime_agent.stop_reason -> string

(** Receipt terminal-reason projection for the runtime-stop axis. Normal
    completion and observational execution-limit stops serialise as canonical
    [Keeper_turn_disposition.Success]. *)
val receipt_terminal_reason_code_of_stop_reason : Runtime_agent.stop_reason -> string

val sandbox_kind_of_meta : Keeper_meta_contract.keeper_meta -> Keeper_types_profile_sandbox.sandbox_profile
val to_json : t -> Yojson.Safe.t

(** One deferred lane as [{"runtime": _, "reason": _}], or [`Null]. Re-exported
    from [Keeper_execution_receipt_types] so the decision record writes the two
    lanes in the shape the receipt writes them. *)
val degraded_retry_json :
  Keeper_error_classify.degraded_retry option -> Yojson.Safe.t

(** Operator-facing classification of a finished turn. Closed set.

    Producer is [operator_disposition]; consumers
    ([needs_operator_broadcast], dashboard JSON, broadcast payload)
    pattern-match exhaustively. The wire form is byte-compatible with the
    pre-typing string ([operator_disposition_kind_to_string]). *)
type operator_disposition_kind =
  | Disp_pass
  | Disp_fail_open_next_runtime
  | Disp_retry_later
  (** The terminal turn did not fall through to another runtime. The Keeper
      remains live and may retry on a later keepalive cycle. *)
  | Disp_pass_next_model
  | Disp_operator_action_required
  (** The turn is terminal and names a known operator-only repair. No runtime
      continuation or fallback is claimed. *)
  | Disp_user_cancelled
  | Disp_skipped
  | Disp_unknown

val operator_disposition_kind_to_string : operator_disposition_kind -> string
val operator_disposition_kind_of_string : string -> operator_disposition_kind option

(** Reason paired with [operator_disposition_kind]. Closed set; the wire
    form is byte-compatible with the pre-typing string. *)
type operator_disposition_reason =
  | Reason_healthy
  | Reason_runtime_exhausted
  | Reason_config_invalid
  (** A setting the runtime rejected before provider dispatch
      ({!Keeper_terminal_reason.Config_invalid}). Paired with
      [Disp_operator_action_required]; the operator edits the runtime's toml.
      The receipt does not claim a fallback that did not happen. *)
  | Reason_authorization_refused
  (** The provider refused the request under authorization before the turn
      could proceed ({!Keeper_terminal_reason.Authorization_refused}). Paired
      with [Disp_operator_action_required] for the same reason as before the
      split: the wire carries weekly and five-hour usage limits, which hold
      that runtime for days, so the operator moves the slot rather than
      waiting. Kept apart from [Reason_config_invalid] because the operator
      does a different thing for each. *)
  | Reason_degraded_retry
  | Reason_runtime_fallback
  | Reason_transient_runtime_retry
  (** A retry-recoverable transient provider-runtime failure
      ([api_error_timeout] / [api_error_network]) that terminally failed this
      turn after neither a degraded retry nor cross-runtime fallback occurred.
      Paired with [Disp_retry_later]: a later keepalive cycle may retry, but the
      receipt does not claim same-turn continuation. *)
  | Reason_provider_runtime_error
  (** A terminal provider rejection or parse/runtime failure after neither a
      degraded retry nor cross-runtime fallback occurred. Paired with
      [Disp_retry_later]: a later keepalive cycle may retry, but the receipt
      does not claim same-turn lane continuation. *)
  | Reason_internal_error
  | Reason_input_required
  | Reason_cancelled
  | Reason_phase_skipped
  | Reason_transcript_corruption
  | Reason_official_client_recovery_required
  (** A durable official-client session refused its claim before provider
      dispatch and remains held until explicit recovery resolution. Paired
      with [Disp_operator_action_required]; no runtime continuation or
      fallback is claimed. *)
  | Reason_provider_attempt_effect_fenced
  (** The provider attempt did not prove whether an effect occurred. Paired
      with [Disp_unknown] so operator attention remains required, and the
      receipt is not counted as an unmapped classifier regression. *)
  | Reason_tool_correction_lost
  (** The fenced turn also recorded typed pre_tool_use rejections
      (masc#28885). Same [Disp_unknown] pairing as
      [Reason_provider_attempt_effect_fenced]; the label separates a lost
      correction from an ordinary fenced provider failure. *)
  | Reason_accept_rejected
  (** The provider answered and MASC's own accept contract found nothing
      usable in the response. Paired with [Disp_fail_open_next_runtime]: no
      operator broadcast, because the keeper carries on and the action this
      points at is a lane's output budget, not an incident. Reached only when
      no degraded retry or runtime fallback claimed the receipt first — those
      say what the system did about it, which is the more specific fact. *)
  | Reason_terminal_effect_failed
  (** The tool that ends the turn by producing an external artifact failed, or
      returned no typed receipt for what it did. Paired with [Disp_unknown]:
      whether the artifact reached the outside world is unknown, the turn is
      never replayed and the stimulus is retired, so a human decides. Same
      pairing as [Reason_provider_attempt_effect_fenced] and
      [Reason_tool_correction_lost]; only the label differs. *)
  | Reason_unmapped_runtime_state

val operator_disposition_reason_to_string : operator_disposition_reason -> string

(** Derived display pair (disposition, reason) computed from receipt fields.
    Exposed for test access; the runtime path consumes it via [append]. *)
val operator_disposition : t -> operator_disposition_kind * operator_disposition_reason

(** [needs_operator_broadcast disposition] returns true when the disposition
    indicates a silent dead-end that operators must be notified about. *)
val needs_operator_broadcast : operator_disposition_kind -> bool

val append : Workspace.config -> t -> unit
val latest_json : Workspace.config -> string -> Yojson.Safe.t option

(** The newest receipt's terminal fields, read back from the store. Labels are
    prefixed so they do not collide with {!t}'s. *)
type latest_receipt_summary =
  { latest_outcome : outcome_kind
  ; latest_terminal_reason_code : string
  ; latest_error_message : string option
    (** [error.message]; [to_json] writes the error as a nested object. *)
  ; latest_ended_at : string
  }

(** What the receipt store says about a Keeper's newest turn. The store being
    empty, its newest row lacking a terminal field, and the store failing to
    read are separate answers, so a reader never presents one as another. *)
type latest_receipt_reading =
  | No_receipt
  | Latest_receipt of latest_receipt_summary
  | Latest_receipt_undecodable of { field : string }
  | Receipt_store_unreadable of Dated_jsonl.read_error

(** Newest parsed receipt row of [keeper_name]. Malformed JSON rows are
    skipped, as {!latest_json} skips them. *)
val read_latest_receipt : Workspace.config -> string -> latest_receipt_reading
val latest_json_by_keeper : Workspace.config -> string list -> (string * Yojson.Safe.t) list
