import '../src/styles/ds-theme-tokens.css'
import '../src/styles/primitives.css'
import '../src/styles/layout.css'
import '../src/styles/layers.css'
import '../src/styles/kpi.css'
import '../src/styles/rail.css'
import '../src/styles/deck.css'
import '../src/styles/drawer.css'
import '../src/styles/swimlanes.css'
import '../src/styles/code.css'
import '../src/styles/styleseed-theme.css'
import '../src/styles/styleseed-base.css'
import '../src/styles/global.css'
import '../src/styles/tokens.css'
import '../src/styles/paper-theme.css'
import '../src/styles/keeper-workspace.css'
import '../src/styles/copilot-dock.css'
import '../src/styles/states.css'
import '../src/styles/ss-keeper-v2-bridge.css'
import.meta.glob('../src/styles/*-v2.css', { eager: true })
import '../src/styles/keeper-v2/colors_and_type.css'
import '../src/styles/keeper-v2/v2.css'
import '../src/styles/keeper-v2/surfaces.css'
import '../src/styles/keeper-v2/dock.css'
import '../src/styles/keeper-v2/craft.css'
import '../src/styles/keeper-v2/inspector.css'
import '../src/styles/keeper-v2/perf.css'
import '../src/styles/keeper-v2/fleet.css'
import '../src/styles/keeper-v2/logs.css'
import '../src/styles/keeper-v2/keeper-config.css'
import '../src/styles/keeper-v2/fusion.css'
import '../src/styles/keeper-v2/memory.css'
import '../src/styles/keeper-v2/schedule.css'
import '../src/styles/keeper-v2/runtime.css'
import '../src/styles/keeper-v2/ops-cluster.css'
import '../src/styles/keeper-v2/prompt-book.css'
import '../src/styles/keeper-v2/verify.css'
import '../src/styles/keeper-v2/registry.css'
import '../src/styles/keeper-v2/monitor.css'
import '../src/styles/keeper-v2/lanes.css'
import '../src/styles/keeper-v2/tempered.css'
import '../src/styles/mobile-operator-targets.css'
import {h,render} from 'preact';
import {SettingsSurface} from '../src/components/settings-surface';
import {setStoredToken} from '../src/api/core';
setStoredToken('synthetic-local-token');
render(h('main',{class:'v2-app',style:'height:100vh'},[h('p',{style:'padding:12px;color:#89a;background:#10141d'},'Synthetic local API fixtures · production Settings component · not deployment proof'),h(SettingsSurface,{})]),document.querySelector('#fixture')!);
