name = "horizon-light"
light = true

[palette]
base00 = "fdf0ed"
base01 = "fadad1"
base02 = "f9cbbe"
base03 = "bdb3b1"
base04 = "948c8a"
base05 = "403c3d"
base06 = "302c2d"
base07 = "201c1d"
base08 = "f7939b"
base09 = "f6661e"
base0a = "fbe0d9"
base0b = "94e1b0"
base0c = "dc3318"
base0d = "da103f"
base0e = "1d8991"
base0f = "e58c92"
