name = "msx-retro"
light = false

[palette]
base00 = "1a1a2e"
base01 = "24243e"
base02 = "32325d"
base03 = "4a4a55"
base04 = "b4b4c4"
base05 = "ffffff"
base06 = "f6ecde"
base07 = "ffffff"
base08 = "ff6b5e"
base09 = "f58124"
base0a = "ffd23e"
base0b = "4fd06a"
base0c = "52e9e0"
base0d = "6a79ff"
base0e = "ff6bd6"
base0f = "b979ff"
