// Closed vocabulary accepted at the dashboard's server-push boundary.
// The static SSEEventType sum and runtime decoder are derived from this tuple.
export const SSE_APPROVAL_PENDING_EVENT = 'approval:pending'
export const SSE_APPROVAL_RESOLVED_EVENT = 'approval:resolved'
export const SSE_APPROVAL_AUDIT_EVENT = 'approval:audit'
export const SSE_APPROVAL_SUMMARY_UPDATED_EVENT = 'approval:summary_updated'

export const SSE_EVENT_TYPES = [
  'agent_bound',
  'masc/agent_bound',
  'agent_unbound',
  'masc/agent_unbound',
  'broadcast',
  'masc/broadcast',
  'task_update',
  'masc/task_claimed',
  'board_post',
  'masc/board_post',
  'board_comment',
  'masc/board_comment',
  'board_delete',
  'masc/board_delete',
  'post_created',
  'comment_added',
  'post_voted',
  'comment_voted',
  'reaction_changed',
  'heartbeat',
  'keeper_heartbeat',
  'keeper_handoff',
  'masc/keeper_handoff',
  'keeper_compaction',
  'masc/keeper_compaction',
  'keeper_guardrail',
  'masc/keeper_guardrail',
  'keeper_phase_changed',
  'keeper_composite_changed',
  'keeper_chat_appended',
  'keeper_chat_operation_event',
  'keeper_waiting_inventory_changed',
  'keeper_compaction_snapshots_changed',
  'agent_core_telemetry_sample',
  'ide_cursor_changed',
  'ide:presence',
  'keeper_tool_call',
  'masc/keeper_tool_call',
  'keeper_tool_skipped',
  'keeper_turn_complete',
  'masc/keeper_turn_complete',
  'fusion_run_status',
  'internal_agent_runs_changed',
  'client_input_approved',
  'client_input_rejected',
  'client_input_updated',
  'runtime_param_changed',
  SSE_APPROVAL_PENDING_EVENT,
  SSE_APPROVAL_RESOLVED_EVENT,
  SSE_APPROVAL_AUDIT_EVENT,
  SSE_APPROVAL_SUMMARY_UPDATED_EVENT,
  'gate_mode_changed',
  'project_snapshot',
  'namespace_truth_snapshot',
  'execution_snapshot',
  'operator_snapshot',
  'operator_digest',
  'transport_health_snapshot',
  'audit_event',
  'masc/audit_event',
  'masc:audit_event',
  'agent_core:masc:audit_event',
  'activity',
  'activity_graph_changed',
  'agent_core:masc:keeper:lifecycle',
  'agent_core:masc:trust_updated',
  'agent_core:masc:reputation_changed',
  'agent_core:masc:harness:verdict_recorded',
  'agent_core:masc:harness:pre_compact',
  'agent_core:masc:harness:handoff',
  'agent_core:agent_started',
  'agent_core:agent_completed',
  'agent_core:agent_yielded',
  'agent_core:agent_input_required',
  'agent_core:agent_failed',
  'agent_core:tool_called',
  'agent_core:tool_completed',
  'agent_core:tool_approval_completed',
  'agent_core:turn_started',
  'agent_core:turn_completed',
  'agent_core:turn_ready',
  'agent_core:handoff_requested',
  'agent_core:handoff_completed',
  'agent_core:context_compacted',
  'agent_core:context_compact_started',
  'agent_core:content_replacement_replaced',
  'agent_core:content_replacement_kept',
  'agent_core:slot_scheduler_observed',
  'agent_core:task_state_changed',
  'agent_core:telemetry_event',
  'agent_core:runtime.agent_completed',
  'agent_core:runtime.artifact_attached',
  'agent_core:runtime.session_completed',
  'agent_core:durable:llm_request',
  'agent_core:durable:llm_response',
  'agent_core:durable:error_occurred',
  'agent_core:durable:turn_started',
  'agent_core:durable:tool_called',
  'agent_core:durable:tool_completed',
  'agent_core:durable:state_transition',
  'agent_core:durable:checkpoint_saved',
  'agent_core:relay_dropped',
] as const

export type SSEEventType = (typeof SSE_EVENT_TYPES)[number]

const SSE_EVENT_TYPE_SET: ReadonlySet<string> = new Set(SSE_EVENT_TYPES)

export function isSSEEventType(value: unknown): value is SSEEventType {
  return typeof value === 'string' && SSE_EVENT_TYPE_SET.has(value)
}
