import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

const TARGET_FILES = [
  'design-system/headless-preact/use-inline-suggestion.ts',
  'design-system/headless-preact/use-collaboration.ts',
  'src/api/dashboard-runtime.ts',
  'src/api/dashboard.ts',
  'src/api/gate.ts',
  'src/api/goal-loop.ts',
  'src/api/schemas/runtime.ts',
  'src/api/schemas/dashboard-config.ts',
  'src/api/schemas/provider-logs.ts',
  'src/api/transport-health.ts',
  'src/components/common/async-container.ts',
  'src/components/common/empty-state.ts',
  'src/components/common/feedback-state.ts',
  'src/components/common/markdown.ts',
  'src/components/connector-status.ts',
  'src/components/fleet-fsm-matrix.ts',
  'src/components/goal-loop-panel.ts',
  'src/components/harness-health-state.ts',
  'src/components/harness-health.ts',
  'src/components/journey-panel.ts',
  'src/components/journey-waterfall-state.ts',
  'src/components/keeper-detail-body.ts',
  'src/components/keeper-sse-match.ts',
  'src/components/keeper-turn-inspector.ts',
  'src/components/keeper-tool-call-inspector.ts',
  'src/components/keeper-tool-telemetry.ts',
  'src/components/logs.ts',
  'src/components/mission.ts',
  'src/components/runtime-monitor.ts',
  'src/components/session-trace/session-trace-live-store.ts',
  'src/components/status.ts',
  'src/components/transport-health.ts',
  'src/dashboard-ws.ts',
  'src/goal-loop-status.ts',
  'src/keeper-actions.ts',
  'src/keeper-chat-pending.ts',
  'src/keeper-runtime.ts',
  'src/lib/async-state.ts',
  'src/components/common/normalize.ts',
  'src/runtime-counts.ts',
  'src/schemas/sse-event-payload.ts',
  'src/schemas/sse.ts',
  'src/sse.ts',
  'src/sse-store.ts',
  'src/tab-refresh.ts',
  'src/tool-call-output-store.ts',
  'src/types/sse.ts',
]

const TEST_FILES = [
  'design-system/headless-preact/use-inline-suggestion.test.ts',
  'design-system/headless-preact/use-collaboration.test.ts',
  'design-system/headless-preact/use-tabs.test.ts',
  'src/api/schemas/runtime.test.ts',
  'src/api/schemas/dashboard-config.test.ts',
  'src/cb-shared-telemetry-source.test.ts',
  'src/components/common/markdown.test.ts',
  'src/components/common/rich-content.test.ts',
  'src/components/common/window.test.ts',
  'src/components/common/cytoscape-fsm.test.ts',
  'src/components/auth-status.test.ts',
  'src/components/connector-status.test.ts',
  'src/components/fleet-fsm-matrix.test.ts',
  'src/components/goal-loop-panel.test.ts',
  'src/components/ide/ide-activity-panel.test.ts',
  'src/components/journey-panel.test.ts',
  'src/components/journey-waterfall-state.test.ts',
  'src/components/keeper-turn-inspector.test.ts',
  'src/components/keeper-sse-match.test.ts',
  'src/components/keeper-tool-call-inspector.test.ts',
  'src/components/logs.test.ts',
  'src/components/session-trace/session-trace-state.test.ts',
  'src/components/transport-health.test.ts',
  'src/dashboard-ws.test.ts',
  'src/goal-loop-status.test.ts',
  'src/keeper-actions.test.ts',
  'src/keeper-chat-store.test.ts',
  'src/lib/async-state.test.ts',
  'src/runtime-counts.test.ts',
  'src/schemas/sse-event-payload.test.ts',
  'src/schemas/sse.test.ts',
  'src/sse-store.test.ts',
  'src/styles/approvals-css-ownership.test.ts',
  'src/styles/chat-blocks-v2.test.ts',
  'src/styles/css-test-utils.ts',
  'src/styles/paper-theme.test.ts',
  'src/styles/skin-v2-paper.test.ts',
]

const DEFAULT_PROJECT_FILES = [
  'design-system/headless-preact/use-inline-suggestion.ts',
  'design-system/headless-preact/use-inline-suggestion.test.ts',
  'design-system/headless-preact/use-collaboration.ts',
  'design-system/headless-preact/use-collaboration.test.ts',
  'design-system/headless-preact/use-tabs.test.ts',
]

export default tseslint.config(
  {
    ignores: ['dist/**', 'coverage/**'],
  },
  {
    files: TARGET_FILES,
    languageOptions: {
      parser: tseslint.parser,
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        projectService: {
          allowDefaultProject: DEFAULT_PROJECT_FILES,
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'react-hooks': reactHooks,
    },
    rules: {
      'no-nested-ternary': 'error',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
    },
  },
  {
    files: ['src/api/gate.ts', 'src/api/transport-health.ts', 'src/components/common/normalize.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
    },
  },
  {
    files: TEST_FILES,
    languageOptions: {
      parser: tseslint.parser,
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        projectService: {
          allowDefaultProject: DEFAULT_PROJECT_FILES,
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
)
