/*
  Generated by atdts from type definitions in 'sse_event_generated.atd'.

  Type-safe translations from/to JSON

  For each type 'Foo', there is a pair of functions:
  - 'writeFoo': convert a 'Foo' value into a JSON-compatible value.
  - 'readFoo': convert a JSON-compatible value into a TypeScript value
    of type 'Foo'.
*/

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

export type AgentStartedPayload = {
  agent_name: string;
  task_id: string;
}

export type ToolCalledPayload = {
  agent_name: string;
  tool_name: string;
}

export type ToolCompletedPayload = {
  agent_name: string;
  tool_name: string;
}

export type TurnStartedPayload = {
  agent_name: string;
  turn: number /*int*/;
}

export type TurnCompletedPayload = {
  agent_name: string;
  turn: number /*int*/;
}

export type TurnReadyPayload = {
  agent_name: string;
  turn: number /*int*/;
  count: number /*int*/;
  names_hash: string;
  tool_names: string[];
}

export type HandoffRequestedPayload = {
  from_agent: string;
  to_agent: string;
  reason: string;
}

export type HandoffCompletedPayload = {
  from_agent: string;
  to_agent: string;
  elapsed_s: number;
}

export type AgentCompletedPayload = {
  agent_name: string;
  task_id: string;
  elapsed_s: number;
}

export type JsonValue = any

export type AgentFailedPayload = {
  agent_name: string;
  task_id: string;
  elapsed_s: number;
  error: string;
  error_domain: string;
  error_code: string;
  error_retryable: boolean;
  error_detail: JsonValue;
}

export function writeAgentStartedPayload(x: AgentStartedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('AgentStartedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'task_id': _atd_write_required_field('AgentStartedPayload', 'task_id', _atd_write_string, x.task_id, x),
  };
}

export function readAgentStartedPayload(x: any, context: any = x): AgentStartedPayload {
  return {
    agent_name: _atd_read_required_field('AgentStartedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    task_id: _atd_read_required_field('AgentStartedPayload', 'task_id', _atd_read_string, x['task_id'], x),
  };
}

export function writeToolCalledPayload(x: ToolCalledPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('ToolCalledPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'tool_name': _atd_write_required_field('ToolCalledPayload', 'tool_name', _atd_write_string, x.tool_name, x),
  };
}

export function readToolCalledPayload(x: any, context: any = x): ToolCalledPayload {
  return {
    agent_name: _atd_read_required_field('ToolCalledPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    tool_name: _atd_read_required_field('ToolCalledPayload', 'tool_name', _atd_read_string, x['tool_name'], x),
  };
}

export function writeToolCompletedPayload(x: ToolCompletedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('ToolCompletedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'tool_name': _atd_write_required_field('ToolCompletedPayload', 'tool_name', _atd_write_string, x.tool_name, x),
  };
}

export function readToolCompletedPayload(x: any, context: any = x): ToolCompletedPayload {
  return {
    agent_name: _atd_read_required_field('ToolCompletedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    tool_name: _atd_read_required_field('ToolCompletedPayload', 'tool_name', _atd_read_string, x['tool_name'], x),
  };
}

export function writeTurnStartedPayload(x: TurnStartedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('TurnStartedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'turn': _atd_write_required_field('TurnStartedPayload', 'turn', _atd_write_int, x.turn, x),
  };
}

export function readTurnStartedPayload(x: any, context: any = x): TurnStartedPayload {
  return {
    agent_name: _atd_read_required_field('TurnStartedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    turn: _atd_read_required_field('TurnStartedPayload', 'turn', _atd_read_int, x['turn'], x),
  };
}

export function writeTurnCompletedPayload(x: TurnCompletedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('TurnCompletedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'turn': _atd_write_required_field('TurnCompletedPayload', 'turn', _atd_write_int, x.turn, x),
  };
}

export function readTurnCompletedPayload(x: any, context: any = x): TurnCompletedPayload {
  return {
    agent_name: _atd_read_required_field('TurnCompletedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    turn: _atd_read_required_field('TurnCompletedPayload', 'turn', _atd_read_int, x['turn'], x),
  };
}

export function writeTurnReadyPayload(x: TurnReadyPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('TurnReadyPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'turn': _atd_write_required_field('TurnReadyPayload', 'turn', _atd_write_int, x.turn, x),
    'count': _atd_write_required_field('TurnReadyPayload', 'count', _atd_write_int, x.count, x),
    'names_hash': _atd_write_required_field('TurnReadyPayload', 'names_hash', _atd_write_string, x.names_hash, x),
    'tool_names': _atd_write_required_field('TurnReadyPayload', 'tool_names', _atd_write_array(_atd_write_string), x.tool_names, x),
  };
}

export function readTurnReadyPayload(x: any, context: any = x): TurnReadyPayload {
  return {
    agent_name: _atd_read_required_field('TurnReadyPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    turn: _atd_read_required_field('TurnReadyPayload', 'turn', _atd_read_int, x['turn'], x),
    count: _atd_read_required_field('TurnReadyPayload', 'count', _atd_read_int, x['count'], x),
    names_hash: _atd_read_required_field('TurnReadyPayload', 'names_hash', _atd_read_string, x['names_hash'], x),
    tool_names: _atd_read_required_field('TurnReadyPayload', 'tool_names', _atd_read_array(_atd_read_string), x['tool_names'], x),
  };
}

export function writeHandoffRequestedPayload(x: HandoffRequestedPayload, context: any = x): any {
  return {
    'from_agent': _atd_write_required_field('HandoffRequestedPayload', 'from_agent', _atd_write_string, x.from_agent, x),
    'to_agent': _atd_write_required_field('HandoffRequestedPayload', 'to_agent', _atd_write_string, x.to_agent, x),
    'reason': _atd_write_required_field('HandoffRequestedPayload', 'reason', _atd_write_string, x.reason, x),
  };
}

export function readHandoffRequestedPayload(x: any, context: any = x): HandoffRequestedPayload {
  return {
    from_agent: _atd_read_required_field('HandoffRequestedPayload', 'from_agent', _atd_read_string, x['from_agent'], x),
    to_agent: _atd_read_required_field('HandoffRequestedPayload', 'to_agent', _atd_read_string, x['to_agent'], x),
    reason: _atd_read_required_field('HandoffRequestedPayload', 'reason', _atd_read_string, x['reason'], x),
  };
}

export function writeHandoffCompletedPayload(x: HandoffCompletedPayload, context: any = x): any {
  return {
    'from_agent': _atd_write_required_field('HandoffCompletedPayload', 'from_agent', _atd_write_string, x.from_agent, x),
    'to_agent': _atd_write_required_field('HandoffCompletedPayload', 'to_agent', _atd_write_string, x.to_agent, x),
    'elapsed_s': _atd_write_required_field('HandoffCompletedPayload', 'elapsed_s', _atd_write_float, x.elapsed_s, x),
  };
}

export function readHandoffCompletedPayload(x: any, context: any = x): HandoffCompletedPayload {
  return {
    from_agent: _atd_read_required_field('HandoffCompletedPayload', 'from_agent', _atd_read_string, x['from_agent'], x),
    to_agent: _atd_read_required_field('HandoffCompletedPayload', 'to_agent', _atd_read_string, x['to_agent'], x),
    elapsed_s: _atd_read_required_field('HandoffCompletedPayload', 'elapsed_s', _atd_read_float, x['elapsed_s'], x),
  };
}

export function writeAgentCompletedPayload(x: AgentCompletedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('AgentCompletedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'task_id': _atd_write_required_field('AgentCompletedPayload', 'task_id', _atd_write_string, x.task_id, x),
    'elapsed_s': _atd_write_required_field('AgentCompletedPayload', 'elapsed_s', _atd_write_float, x.elapsed_s, x),
  };
}

export function readAgentCompletedPayload(x: any, context: any = x): AgentCompletedPayload {
  return {
    agent_name: _atd_read_required_field('AgentCompletedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    task_id: _atd_read_required_field('AgentCompletedPayload', 'task_id', _atd_read_string, x['task_id'], x),
    elapsed_s: _atd_read_required_field('AgentCompletedPayload', 'elapsed_s', _atd_read_float, x['elapsed_s'], x),
  };
}

export function writeJsonValue(x: JsonValue, context: any = x): any {
  return ((x: any, context): any => x)(x, context);
}

export function readJsonValue(x: any, context: any = x): JsonValue {
  return ((x: any, context): any => x)(x, context);
}

export function writeAgentFailedPayload(x: AgentFailedPayload, context: any = x): any {
  return {
    'agent_name': _atd_write_required_field('AgentFailedPayload', 'agent_name', _atd_write_string, x.agent_name, x),
    'task_id': _atd_write_required_field('AgentFailedPayload', 'task_id', _atd_write_string, x.task_id, x),
    'elapsed_s': _atd_write_required_field('AgentFailedPayload', 'elapsed_s', _atd_write_float, x.elapsed_s, x),
    'error': _atd_write_required_field('AgentFailedPayload', 'error', _atd_write_string, x.error, x),
    'error_domain': _atd_write_required_field('AgentFailedPayload', 'error_domain', _atd_write_string, x.error_domain, x),
    'error_code': _atd_write_required_field('AgentFailedPayload', 'error_code', _atd_write_string, x.error_code, x),
    'error_retryable': _atd_write_required_field('AgentFailedPayload', 'error_retryable', _atd_write_bool, x.error_retryable, x),
    'error_detail': _atd_write_required_field('AgentFailedPayload', 'error_detail', writeJsonValue, x.error_detail, x),
  };
}

export function readAgentFailedPayload(x: any, context: any = x): AgentFailedPayload {
  return {
    agent_name: _atd_read_required_field('AgentFailedPayload', 'agent_name', _atd_read_string, x['agent_name'], x),
    task_id: _atd_read_required_field('AgentFailedPayload', 'task_id', _atd_read_string, x['task_id'], x),
    elapsed_s: _atd_read_required_field('AgentFailedPayload', 'elapsed_s', _atd_read_float, x['elapsed_s'], x),
    error: _atd_read_required_field('AgentFailedPayload', 'error', _atd_read_string, x['error'], x),
    error_domain: _atd_read_required_field('AgentFailedPayload', 'error_domain', _atd_read_string, x['error_domain'], x),
    error_code: _atd_read_required_field('AgentFailedPayload', 'error_code', _atd_read_string, x['error_code'], x),
    error_retryable: _atd_read_required_field('AgentFailedPayload', 'error_retryable', _atd_read_bool, x['error_retryable'], x),
    error_detail: _atd_read_required_field('AgentFailedPayload', 'error_detail', readJsonValue, x['error_detail'], x),
  };
}


/////////////////////////////////////////////////////////////////////
// Runtime library
/////////////////////////////////////////////////////////////////////

export type Option<T> = null | { value: T }

function _atd_missing_json_field(type_name: string, json_field_name: string) {
    throw new Error(`missing field '${json_field_name}'` +
                    ` in JSON object of type '${type_name}'`)
}

function _atd_missing_ts_field(type_name: string, ts_field_name: string) {
    throw new Error(`missing field '${ts_field_name}'` +
                    ` in TypeScript object of type '${type_name}'`)
}

function _atd_bad_json(expected_type: string, json_value: any, context: any) {
  let value_str = JSON.stringify(json_value)
  if (value_str.length > 200)
    value_str = value_str.substring(0, 200) + '…';

  throw new Error(`incompatible JSON value where` +
                  ` type '${expected_type}' was expected: '${value_str}'.` +
                  ` Occurs in '${JSON.stringify(context)}'.`)
}

function _atd_bad_ts(expected_type: string, ts_value: any, context: any) {
  let value_str = JSON.stringify(ts_value)
  if (value_str.length > 200)
    value_str = value_str.substring(0, 200) + '…';

  throw new Error(`incompatible TypeScript value where` +
                  ` type '${expected_type}' was expected: '${value_str}'.` +
                  ` Occurs in '${JSON.stringify(context)}'.`)
}

function _atd_check_json_tuple(len: number /*int*/, x: any, context: any) {
  if (! Array.isArray(x) || x.length !== len)
    _atd_bad_json('tuple of length ' + len, x, context);
}

function _atd_read_unit(x: any, context: any): null {
  if (x === null)
    return null
  else {
    _atd_bad_json('null', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_bool(x: any, context: any): boolean {
  if (typeof x === 'boolean')
    return x
  else {
    _atd_bad_json('boolean', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_int(x: any, context: any): number /*int*/ {
  if (Number.isInteger(x))
    return x
  else {
    _atd_bad_json('integer', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_float(x: any, context: any): number {
  if (isFinite(x))
    return x
  else {
    _atd_bad_json('number', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_string(x: any, context: any): string {
  if (typeof x === 'string')
    return x
  else {
    _atd_bad_json('string', x, context)
    throw new Error('impossible')
  }
}

function _atd_read_required_field<T>(type_name: string,
                                     field_name: string,
                                     read_elt: (x: any, context: any) => T,
                                     x: any,
                                     context: any): T {
  if (x === undefined) {
    _atd_missing_json_field(type_name, field_name)
    throw new Error('impossible')
  }
  else
    return read_elt(x, context)
}

function _atd_read_optional_field<T>(read_elt: (x: any, context: any) => T,
                                     x: any,
                                     context: any): T {
  if (x === undefined || x === null)
    return x
  else
    return read_elt(x, context)
}

function _atd_read_field_with_default<T>(read_elt: (x: any, context: any) => T,
                                         default_: T,
                                         x: any,
                                         context: any): T {
  if (x === undefined || x === null)
    return default_
  else
    return read_elt(x, context)
}

function _atd_read_option<T>(read_elt: (x: any, context: any) => T):
  (x: any, context: any) => Option<T> {
  function read_option(x: any, context: any): Option<T> {
    if (x === 'None')
      return null
    else {
      _atd_check_json_tuple(2, x, context);
      switch (x[0]) {
        case 'Some':
          return { value: read_elt(x[1], context) }
        default:
          _atd_bad_json('option', x, context)
          throw new Error('impossible')
      }
    }
  }
  return read_option
}

function _atd_read_nullable<T>(read_elt: (x: any, context: any) => T):
  (x: any, context: any) => T | null {
  function read_nullable(x: any, context: any): T | null {
    if (x === null)
      return null
    else
      return read_elt(x, context)
  }
  return read_nullable
}

function _atd_read_array<T>(read_elt: (x: any, context: any) => T):
  (elts: any, context: any) => T[] {
  function read_array(elts: any, context: any): T[] {
    if (Array.isArray(elts))
      return elts.map((x) => read_elt(x, elts))
    else {
      _atd_bad_json('array', elts, context)
      throw new Error('impossible')
    }
  }
  return read_array
}

function _atd_read_assoc_array_into_map<K, V>(
    read_key: (key: any, context: any) => K,
    read_value: (value: any, context: any) => V
  ): (x: any, context: any) => Map<K, V> {
  function read_assoc(elts: any, context: any): Map<K, V> {
    if (Array.isArray(elts)) {
      const res = new Map<K, V>([])
      for (const x of elts) {
        if (Array.isArray(x) && x.length === 2)
          res.set(read_key(x[0], x), read_value(x[1], x))
        else {
          _atd_bad_json('pair', x, elts)
          throw new Error('impossible')
        }
      }
      return res
    }
    else {
      _atd_bad_json('array', elts, context)
      throw new Error('impossible')
    }
  }
  return read_assoc
}

function _atd_read_assoc_object_into_map<T>(
    read_value: (value: any, context: any) => T
  ): (x: any, context: any) => Map<string, T> {
  function read_assoc(elts: any, context: any): Map<string, T> {
    if (typeof elts === 'object') {
      const res = new Map<string, T>([])
      for (const [key, value] of Object.entries(elts))
        res.set(key, read_value(value, elts))
      return res
    }
    else {
      _atd_bad_json('object', elts, context)
      throw new Error('impossible')
    }
  }
  return read_assoc
}

function _atd_read_assoc_object_into_array<T>(
    read_value: (value: any, context: any) => T
  ): (x: any, context: any) => [string, T][] {
  function read_assoc(elts: any, context: any): [string, T][] {
    if (typeof elts === 'object') {
      const res: [string, T][] = []
      for (const [key, value] of Object.entries(elts))
        res.push([key, read_value(value, elts)])
      return res
    }
    else {
      _atd_bad_json('object', elts, context)
      throw new Error('impossible')
    }
  }
  return read_assoc
}

function _atd_write_unit(x: any, context: any) {
  if (x === null)
    return x
  else {
    _atd_bad_ts('null', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_bool(x: any, context: any): boolean {
  if (typeof x === 'boolean')
    return x
  else {
    _atd_bad_ts('boolean', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_int(x: any, context: any): number /*int*/ {
  if (Number.isInteger(x))
    return x
  else {
    _atd_bad_ts('integer', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_float(x: any, context: any): number {
  if (isFinite(x))
    return x
  else {
    _atd_bad_ts('number', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_string(x: any, context: any): string {
  if (typeof x === 'string')
    return x
  else {
    _atd_bad_ts('string', x, context)
    throw new Error('impossible')
  }
}

function _atd_write_option<T>(write_elt: (x: T, context: any) => any):
   (elts: Option<T>, context: any) => any {
  function write_option(x: Option<T>, context: any): any {
    if (x === null)
      return 'None'
    else
      return ['Some', write_elt(x.value, context)]
  }
  return write_option
}

function _atd_write_nullable<T>(write_elt: (x: T, context: any) => any):
  (x: T | null, context: any) => any {
  function write_option(x: T | null, context: any): any {
    if (x === null)
      return null
    else
      return write_elt(x, context)
  }
  return write_option
}

function _atd_write_array<T>(write_elt: (elt: T, context: any) => any):
  (elts: T[], context: any) => any {
  return ((elts: T[], context: any): any =>
    elts.map((x) => write_elt(x, elts))
  )
}

function _atd_write_assoc_map_to_array<K, V>(
    write_key: (key: K, context: any) => any,
    write_value: (value: V, context: any) => any
  ): (elts: Map<K, V>, context: any) => any {
  function write_assoc(elts: Map<K, V>, context: any): any {
    const res: any = []
    elts.forEach((value: V, key: K) =>
      res.push([write_key(key, elts), write_value(value, elts)])
    )
    return res
  }
  return write_assoc
}

function _atd_write_assoc_map_to_object<T>(
    write_value: (value: T, context: any) => any
  ): (elts: Map<string, T>, context: any) => any {
  function write_assoc(elts: Map<string, T>, context: any): any {
    const res: any = {}
    elts.forEach((value: T, key: string) =>
      res[key] = write_value(value, elts)
    )
    return res
  }
  return write_assoc
}

function _atd_write_assoc_array_to_object<T>(
    write_value: (value: T, context: any) => any
  ): (elts: [string, T][], context: any) => any {
  function write_assoc(elts: [string, T][], context: any): any {
    const res: any = {}
    for (const [key, value] of elts)
      res[key] = write_value(value, elts)
    return res
  }
  return write_assoc
}

function _atd_write_required_field<T>(type_name: string,
                                      field_name: string,
                                      write_elt: (x: T, context: any) => any,
                                      x: T,
                                      context: any): any {
  if (x === undefined) {
    _atd_missing_ts_field(type_name, field_name)
    throw new Error('impossible')
  }
  else
    return write_elt(x, context)
}

function _atd_write_optional_field<T>(write_elt: (x: T, context: any) => any,
                                      x: T | undefined,
                                      context: any): any {
  if (x === undefined || x === null)
    return x
  else
    return write_elt(x, context)
}

function _atd_write_field_with_default<T>(
  write_elt: (x: T, context: any) => any,
  default_: T,
  x: T,
  context: any
): T {
  const value = (x === undefined || x === null) ? default_ : x
  return write_elt(value, context)
}

