#use "lib/string_util/string_util.ml";;
let checks = ref 0;;
let check label expected actual = if expected <> actual then (prerr_endline label; exit 1) else incr checks;;
check "source / RC" false (contains_query_term_ci "source" "RC");;
check "SRC / RC" false (contains_query_term_ci "SRC" "RC");;
check "archive / RC" false (contains_query_term_ci "archive" "RC");;
check "RC1 / RC" false (contains_query_term_ci "RC1" "RC");;
check "RC / RC" true (contains_query_term_ci "RC" "RC");;
check "(rc) / RC" true (contains_query_term_ci "(rc)" "RC");;
check "RC-12 / RC" true (contains_query_term_ci "RC-12" "RC");;
check "release/RC / RC" true (contains_query_term_ci "release/RC" "RC");;
check "RC는 보류한다 / RC" true (contains_query_term_ci "RC는 보류한다" "RC");;
check "CI가 끝났다 / CI" true (contains_query_term_ci "CI가 끝났다" "CI");;
check "city / CI" false (contains_query_term_ci "city" "CI");;
check "SRC policy / RC policy" false (contains_query_term_ci "SRC policy" "RC policy");;
check "policy CIty / policy CI" false (contains_query_term_ci "policy CIty" "policy CI");;
check "source then RC / RC" true (contains_query_term_ci "source then RC" "RC");;
check "소주를 / 소주" true (contains_query_term_ci "소주를" "소주");;
check "release-candidate / release" true (contains_query_term_ci "release-candidate" "release");;
check "task-123 / 12" false (contains_query_term_ci "task-123" "12");;
check " / " false (contains_query_term_ci "" "");;
check "AND fallback excludes word interior" false (contains_all_query_terms_ci "source policy" "RC policy");;
check "AND fallback preserves RC term" true (contains_all_query_terms_ci "RC current policy" "RC policy");;
Printf.printf "PASS %d actual query predicate assertions\n" !checks;;
