let field_summary = Keeper_state_reporting_contract.field_summary
let template_text = Keeper_state_reporting_contract.template_text
let instruction_text = Keeper_state_reporting_contract.instruction_text
