module Format = Stdlib.Format
module Map = Stdlib.Map
module Set = Stdlib.Set
module Queue = Stdlib.Queue
module Hashtbl = Stdlib.Hashtbl
module Mutex = Stdlib.Mutex
module Option = Stdlib.Option
module Result = Stdlib.Result
module Sys = Stdlib.Sys
module Filename = Stdlib.Filename
module List = Stdlib.List
module Array = Stdlib.Array
module String = Stdlib.String
module Char = Stdlib.Char
module Int = Stdlib.Int
module Float = Stdlib.Float
module Random = Stdlib.Random

(** Agent_reputation — Reputation scoring from existing JSONL data

    Computes agent reputation from task transitions, mention inbox,
    and board posts/comments.
    No new storage — reads from existing `.masc/` JSONL files.

    @since Phase 3B — Keeper Deliberation Engine
*)

type agent_reputation = {
  agent_name: string;
  tasks_completed: int; [@default 0]
  tasks_claimed: int; [@default 0]
  completion_rate: float; [@default 0.0]
  mentions_received: int; [@default 0]
  mentions_responded: int; [@default 0]
  response_rate: float; [@default 0.0]
  board_posts: int; [@default 0]
  board_comments: int; [@default 0]
  accountability_score: float; [@default 1.0]
  accountability_risk_band: string; [@default "low"]
  accountability_evidence_coverage: float; [@default 1.0]
  accountability_unsupported_completion_rate: float; [@default 0.0]
  accountability_open_overdue_commitments: int; [@default 0]
  accountability_keeper_name: string; [@default ""]
  accountability_source: string; [@default "none"]
  accountability_source_label: string; [@default "No accountability history"]
  overall_score: float; [@default 0.0]
  (* v2 multi-dimensional scores — additive fields; absent in v1 records
     are interpreted as the neutral default (1.0 for rates, "standard" for level). *)
  execution_reliability: float; [@default 1.0]
  (** Tool-call success rate from the v2 ledger. 0.0–1.0. *)
  goal_adherence: float; [@default 1.0]
  (** Proportion of goal completions that were on-topic and within budget. 0.0–1.0. *)
  safety_compliance: float; [@default 1.0]
  (** Penalty-adjusted safety score; decreases with each sandbox violation. 0.0–1.0. *)
  autonomy_level: string; [@default "standard"]
  (** Derived autonomy envelope: "restricted" | "standard" | "elevated" | "full". *)
  thompson_confidence: float; [@default 0.5]
  (** Thompson Sampling Beta expected value (alpha/(alpha+beta)).
      0.5 is the neutral prior (alpha=1.0, beta=1.0). *)
} [@@deriving yojson { strict = false }]

(** {1 Defaults} *)

let default_reputation ~(agent_name : string) : agent_reputation =
  { agent_name;
    tasks_completed = 0;
    tasks_claimed = 0;
    completion_rate = 0.0;
    mentions_received = 0;
    mentions_responded = 0;
    response_rate = 0.0;
    board_posts = 0;
    board_comments = 0;
    accountability_score = 1.0;
    accountability_risk_band = "low";
    accountability_evidence_coverage = 1.0;
    accountability_unsupported_completion_rate = 0.0;
    accountability_open_overdue_commitments = 0;
    accountability_keeper_name = agent_name;
    accountability_source = "none";
    accountability_source_label = "No accountability history";
    overall_score = 0.0;
    execution_reliability = 1.0;
    goal_adherence = 1.0;
    safety_compliance = 1.0;
    autonomy_level = "standard";
    thompson_confidence = 0.5;
  }

(** {1 JSON Serialization}

    [agent_reputation_to_yojson] and [agent_reputation_of_yojson] are
    generated by [ppx_deriving_yojson].  The wrappers below preserve
    the legacy [option]-returning API for callers that haven't migrated
    to [result] yet. *)

let reputation_to_json : agent_reputation -> Yojson.Safe.t =
  agent_reputation_to_yojson

let reputation_of_json (json : Yojson.Safe.t) : agent_reputation option =
  match agent_reputation_of_yojson json with
  | Ok r when not (String.equal r.agent_name "") -> Some r
  | Ok _ -> None
  | Error msg ->
    Log.Reputation.warn "agent reputation of_json: %s" msg;
    None

(** {1 JSONL Helpers} *)

let persistence_surface = "agent_reputation"

let observe_jsonl_drop ~reason ~delta =
  Prometheus.inc_counter Prometheus.metric_persistence_read_drops
    ~labels:[("surface", persistence_surface); ("reason", reason)]
    ~delta
    ()

let report_jsonl_drop ~reason ~path ~detail ~delta =
  Safe_ops.report_persistence_read_drop
    ~on_drop:(fun () -> observe_jsonl_drop ~reason ~delta)
    ~surface:persistence_surface
    ~reason
    ~path
    ~detail

(** Load a JSONL file, filter out malformed lines. *)
let load_jsonl_safe (path : string) : Yojson.Safe.t list =
  if not (Sys.file_exists path) then []
  else
    try
      let rows, malformed = Fs_compat.load_jsonl_diagnostics path in
      if malformed > 0 then
        report_jsonl_drop
          ~reason:Safe_ops.persistence_read_drop_reason_entry_load_error
          ~path
          ~detail:(Printf.sprintf "%d malformed JSONL line(s)" malformed)
          ~delta:(Float.of_int malformed);
      rows
    with
    | Eio.Cancel.Cancelled _ as e -> raise e
    | exn ->
        report_jsonl_drop
          ~reason:Safe_ops.persistence_read_drop_reason_entry_load_error
          ~path
          ~detail:(Printexc.to_string exn)
          ~delta:1.0;
        []

(** {1 Task Counting from Coord State} *)

(** Count tasks claimed and completed by an agent from the room's task list.
    Reads the canonical Coord backlog so reputation follows the same storage
    path as task transitions. *)
let count_tasks_from_room (config : Coord.config) ~(agent_name : string)
    : int * int =
  let claimed = ref 0 in
  let completed = ref 0 in
  Coord.get_tasks_safe config
  |> List.iter (fun (task : Masc_domain.task) ->
         match task.task_status with
         | Masc_domain.Claimed { assignee; _ }
         | Masc_domain.InProgress { assignee; _ }
         | Masc_domain.AwaitingVerification { assignee; _ }
           when String.equal assignee agent_name ->
             Stdlib.incr claimed
         | Masc_domain.Done { assignee; _ } when String.equal assignee agent_name ->
             Stdlib.incr claimed;
             Stdlib.incr completed
         | Masc_domain.Todo
         | Masc_domain.Claimed _ | Masc_domain.InProgress _ | Masc_domain.AwaitingVerification _
         | Masc_domain.Done _ | Masc_domain.Cancelled _ -> ());
  (!claimed, !completed)

(** {1 Board Counting} *)

(** Count board posts and comments authored by an agent from JSONL files. *)
let count_board_activity (config : Coord.config) ~(agent_name : string)
    : int * int =
  let board_dir = Coord.masc_dir config in
  (* Board posts JSONL *)
  let posts_path = Filename.concat board_dir "board_posts.jsonl" in
  let posts_rows = load_jsonl_safe posts_path in
  let post_count =
    posts_rows
    |> List.filter (fun json ->
        let author = Safe_ops.json_string ~default:"" "author" json in
        String.equal author agent_name)
    |> List.length
  in
  (* Board comments JSONL *)
  let comments_path = Filename.concat board_dir "board_comments.jsonl" in
  let comments_rows = load_jsonl_safe comments_path in
  let comment_count =
    comments_rows
    |> List.filter (fun json ->
        let author = Safe_ops.json_string ~default:"" "author" json in
        String.equal author agent_name)
    |> List.length
  in
  (post_count, comment_count)

(** {1 Mention Counting} *)

let count_mention_activity (config : Coord.config) ~(agent_name : string)
    : int * int =
  let all = Mention_inbox.read_mentions config ~target_agent:agent_name ~limit:10000 in
  let received = List.length all in
  let responded = List_util.count_if (fun r -> Stdlib.Float.compare r.Mention_inbox.read_at 0.0 > 0) all in
  (received, responded)

(** {1 Overall Score Computation} *)

let clamp01 value = Float.max 0.0 (Float.min 1.0 value)

(** {1 Reputation Score Weights}

    Weighted linear combination for overall reputation.
    Rationale: task completion is the primary signal (0.35) because
    it directly measures value delivered. Response rate (0.25) and
    board activity (0.25) are secondary engagement signals.
    Thompson confidence (0.15) captures empirical quality from
    Beta distribution feedback (votes, quality signals).

    Board activity is capped at [board_activity_cap] to prevent
    high-volume low-quality posting from inflating scores.

    TODO(RFC-0001 Phase 3): Register in Runtime_params for tuning. *)
let weight_completion = 0.35
let weight_response   = 0.25
let weight_board      = 0.25
let weight_thompson   = 0.15
let board_activity_cap = 20.0

let compute_accountability_score ~evidence_coverage
    ~unsupported_completion_rate ~open_overdue_commitments : float =
  let overdue_penalty =
    Float.min 0.5 (0.1 *. Float.of_int open_overdue_commitments)
  in
  clamp01
    (evidence_coverage -. unsupported_completion_rate -. overdue_penalty)

let compute_overall_score ~completion_rate ~response_rate
    ~board_posts ~board_comments ~thompson_confidence : float =
  let board_total = Float.of_int (board_posts + board_comments) in
  let board_norm = Float.min 1.0 (board_total /. board_activity_cap) in
  (weight_completion *. completion_rate)
  +. (weight_response *. response_rate)
  +. (weight_board *. board_norm)
  +. (weight_thompson *. thompson_confidence)

(** {1 Accountability Penalty} *)

let keeper_name_of_agent agent_name =
  match Keeper_identity.canonical_keeper_name_from_agent_name agent_name with
  | Some keeper_name -> keeper_name
  | None -> String.trim agent_name

let accountability_metrics (config : Coord.config) ~(agent_name : string) =
  let keeper_name = keeper_name_of_agent agent_name in
  let summary =
    Keeper_accountability.accountability_summary_json config
      ~keeper_name ~agent_name
  in
  let evidence_coverage =
    Safe_ops.json_float ~default:1.0 "evidence_coverage" summary
  in
  let unsupported_completion_rate =
    Safe_ops.json_float ~default:0.0 "unsupported_completion_rate" summary
  in
  let open_overdue_commitments =
    Safe_ops.json_int ~default:0 "open_overdue_commitments" summary
  in
  let risk_band =
    Safe_ops.json_string ~default:"low" "risk_band" summary
  in
  let source =
    Safe_ops.json_string ~default:"none" "source" summary
  in
  let source_label =
    Safe_ops.json_string ~default:"No accountability history" "source_label"
      summary
  in
  let score =
    compute_accountability_score ~evidence_coverage
      ~unsupported_completion_rate ~open_overdue_commitments
  in
  (score, risk_band, evidence_coverage, unsupported_completion_rate,
   open_overdue_commitments, keeper_name, source, source_label)

(** {1 Main Computation} *)

(** Default window for v2 ledger metrics: 14 days matches accountability window. *)
let v2_ledger_window_days = 14

(** {1 Thompson Confidence}

    Compute the Thompson Sampling Beta expected value for an agent.
    Returns 0.5 (neutral prior) when no stats exist or when alpha+beta
    is zero (should not happen given min 0.1 priors, but safe division
    handles the edge case). *)
let thompson_confidence_for_agent (agent_name : string) : float =
  let stats = Thompson_sampling.get_stats agent_name in
  let sum = stats.Thompson_sampling.alpha +. stats.Thompson_sampling.beta in
  if sum > 0.0 then stats.Thompson_sampling.alpha /. sum
  else 0.5

let compute_reputation (config : Coord.config) ~(agent_name : string)
    : agent_reputation =
  let (tasks_claimed, tasks_completed) =
    count_tasks_from_room config ~agent_name
  in
  let completion_rate =
    if tasks_claimed > 0 then
      Float.of_int tasks_completed /. Float.of_int tasks_claimed
    else 0.0
  in
  let (mentions_received, mentions_responded) =
    count_mention_activity config ~agent_name
  in
  let response_rate =
    if mentions_received > 0 then
      Float.of_int mentions_responded /. Float.of_int mentions_received
    else 0.0
  in
  let (board_posts, board_comments) = count_board_activity config ~agent_name in
  let (accountability_score, accountability_risk_band,
       accountability_evidence_coverage,
       accountability_unsupported_completion_rate,
       accountability_open_overdue_commitments,
       accountability_keeper_name,
       accountability_source,
       accountability_source_label) =
    accountability_metrics config ~agent_name
  in
  let thompson_confidence = thompson_confidence_for_agent agent_name in
  let overall_score =
    compute_overall_score ~completion_rate
      ~response_rate ~board_posts ~board_comments ~thompson_confidence
    *. clamp01 accountability_score
  in
  (* v2: pull multi-dimensional metrics from the reputation ledger. *)
  let v2_metrics =
    (try
       Reputation_ledger_v2.compute_ledger_metrics config
         ~agent_id:agent_name ~window_days:v2_ledger_window_days
     with
     | Eio.Cancel.Cancelled _ as e -> raise e
     | _exn ->
       Reputation_ledger_v2.default_ledger_metrics)
  in
  let autonomy =
    Reputation_autonomy.compute_autonomy_level
      ~execution_reliability:v2_metrics.Reputation_ledger_v2.execution_reliability
      ~goal_adherence:v2_metrics.Reputation_ledger_v2.goal_adherence
      ~safety_compliance:v2_metrics.Reputation_ledger_v2.safety_compliance
      ~accountability_score:(clamp01 accountability_score)
  in
  { agent_name;
    tasks_completed; tasks_claimed; completion_rate;
    mentions_received; mentions_responded; response_rate;
    board_posts; board_comments;
    accountability_score;
    accountability_risk_band;
    accountability_evidence_coverage;
    accountability_unsupported_completion_rate;
    accountability_open_overdue_commitments;
    accountability_keeper_name;
    accountability_source;
    accountability_source_label;
    overall_score;
    execution_reliability = v2_metrics.Reputation_ledger_v2.execution_reliability;
    goal_adherence = v2_metrics.Reputation_ledger_v2.goal_adherence;
    safety_compliance = v2_metrics.Reputation_ledger_v2.safety_compliance;
    autonomy_level = Reputation_autonomy.autonomy_level_to_string autonomy;
    thompson_confidence;
  }
