(** Re-export from Keeper_transport_runtime_mcp_policy_of_tool_names. @deprecated Use Keeper_transport_runtime_mcp_policy_of_tool_names directly. *)
include Keeper_transport_runtime_mcp_policy_of_tool_names
