(** Generational Metrics -- Evidence for successor improvement.

    Tracks metrics across agent generations to measure whether successor
    agents perform better than their predecessors. Answers the question:
    "Is the next generation better?"

    Key metrics tracked per generation:
    - Task completion rate
    - Error rate
    - Average task duration
    - Token efficiency (input + output per task)
    - Knowledge retention (via explicit Q&A tests)

    Data is stored in-memory (mutable refs) for quick prototyping.
    Use {!reset} to clear all data between test runs.

    @since 0.4.0 *)

(** {1 Types} *)

(** A single task completion record within a generation.

    Records the outcome of one task including timing, error count,
    and token usage for efficiency analysis. *)
type task_record = {
  generation : int;
      (** Generation number of the cell that executed this task. *)
  task_id : string;
      (** Unique identifier for the task. *)
  completed : bool;
      (** [true] if the task was completed successfully. *)
  duration_ms : int;
      (** Wall-clock duration of the task in milliseconds. *)
  error_count : int;
      (** Number of errors encountered during this task. *)
  input_tokens : int;
      (** Number of input tokens consumed. *)
  output_tokens : int;
      (** Number of output tokens generated. *)
  timestamp : float;
      (** Unix timestamp when the record was created. *)
}

(** A record of a handoff event between two generations.

    Captures the DNA transfer metadata for analyzing handoff quality. *)
type handoff_record = {
  from_generation : int;
      (** Generation of the parent (dividing) cell. *)
  to_generation : int;
      (** Generation of the child (activated) cell. *)
  dna_size : int;
      (** Size of the transferred DNA in characters. *)
  context_ratio : float;
      (** Context usage ratio at the time of handoff (0.0--1.0). *)
  timestamp : float;
      (** Unix timestamp of the handoff. *)
}

(** A knowledge retention test result.

    Tests whether a successor agent retained key knowledge from
    its predecessor by comparing expected vs actual answers. *)
type retention_test = {
  generation : int;
      (** Generation of the cell being tested. *)
  question : string;
      (** The question asked to test retention. *)
  expected : string;
      (** The expected answer (from the predecessor's knowledge). *)
  actual : string;
      (** The actual answer given by the successor. *)
  correct : bool;
      (** [true] if [expected] matches [actual] (case-insensitive). *)
  confidence : float;
      (** Self-reported confidence in the answer (0.0--1.0). *)
}

(** Aggregated summary of a single generation's performance.

    Computed by {!summarize_generation} from individual {!task_record}s. *)
type generation_summary = {
  generation : int;
      (** The generation number. *)
  total_tasks : int;
      (** Total number of tasks attempted. *)
  completed_tasks : int;
      (** Number of tasks completed successfully. *)
  total_errors : int;
      (** Sum of all error counts across tasks. *)
  avg_duration_ms : float;
      (** Average task duration in milliseconds. *)
  total_input_tokens : int;
      (** Total input tokens consumed by this generation. *)
  total_output_tokens : int;
      (** Total output tokens generated by this generation. *)
  knowledge_retention : float option;
      (** Fraction of retention tests passed (0.0--1.0).
          [None] if no retention tests were recorded. *)
}

(** Side-by-side comparison of two generations.

    Delta values indicate relative performance:
    - Positive [completion_delta]: gen B has higher completion rate.
    - Negative [error_delta]: gen B has fewer errors (better).
    - Negative [duration_delta]: gen B is faster (better).
    - Negative [token_delta]: gen B uses fewer tokens (better). *)
type generation_comparison = {
  gen_a : int;
      (** First (typically older) generation. *)
  gen_b : int;
      (** Second (typically newer) generation. *)
  completion_delta : float;
      (** Completion rate difference: B - A. Positive means B is better. *)
  error_delta : float;
      (** Error rate difference: B - A. Negative means B is better. *)
  duration_delta : float;
      (** Average duration difference: B - A. Negative means B is faster. *)
  token_delta : float;
      (** Tokens-per-task difference: B - A. Negative means B is more efficient. *)
  retention_b : float option;
      (** Knowledge retention score for generation B, if tested. *)
  verdict : string;
      (** Overall verdict: ["improved"], ["degraded"], or ["neutral"].
          Based on majority of metric improvements (3+ of 4 = improved). *)
}

(** {1 Recording} *)

(** [record_task ~generation ~task_id ~completed ~duration_ms ~error_count
      ~input_tokens ~output_tokens]
    records a task completion and stores it in the in-memory task list.

    @return the created {!task_record}. *)
val record_task :
  generation:int ->
  task_id:string ->
  completed:bool ->
  duration_ms:int ->
  error_count:int ->
  input_tokens:int ->
  output_tokens:int ->
  task_record

(** [record_handoff ~from_generation ~to_generation ~dna_size ~context_ratio]
    records a handoff event between two generations.

    @return the created {!handoff_record}. *)
val record_handoff :
  from_generation:int ->
  to_generation:int ->
  dna_size:int ->
  context_ratio:float ->
  handoff_record

(** [record_retention_test ~generation ~question ~expected ~actual ~confidence]
    records a knowledge retention test. The [correct] field is computed
    automatically by case-insensitive string comparison of [expected]
    and [actual].

    @return the created {!retention_test}. *)
val record_retention_test :
  generation:int ->
  question:string ->
  expected:string ->
  actual:string ->
  confidence:float ->
  retention_test

(** {1 Analysis} *)

(** [summarize_generation gen] aggregates all task records for generation
    [gen] into a {!generation_summary}.

    @return [None] if no task records exist for the given generation. *)
val summarize_generation : int -> generation_summary option

(** [compare_generations gen_a gen_b] produces a side-by-side comparison
    of two generations based on their {!generation_summary} values.

    The verdict is ["improved"] if 3 or more of the 4 metrics favor gen B,
    ["degraded"] if 1 or fewer, and ["neutral"] otherwise.

    @return [None] if either generation has no task records. *)
val compare_generations : int -> int -> generation_comparison option

(** [format_comparison comp] produces a human-readable multi-line string
    summarizing the comparison, including per-metric deltas and
    better/worse annotations. *)
val format_comparison : generation_comparison -> string

(** {1 Utilities} *)

(** [reset ()] clears all in-memory records (tasks, handoffs, and
    retention tests). Intended for use between test runs. *)
val reset : unit -> unit

(** [to_json ()] exports all recorded tasks and handoffs as a JSON
    object with [tasks] and [handoffs] arrays. *)
val to_json : unit -> Yojson.Safe.t
