let goal_completion_decision = "goal_completion_decision"
let goal_target_type = "goal"
let goal_transition_tool = "masc_goal_transition"
let goal_approval_token_prefix = "goal-approval:"
let goal_decision_approve = "approve"
let goal_decision_reject = "reject"
