(** Private Prometheus metric-name constants. *)

val metric_keeper_passive_loop_detected_total : string
val metric_keeper_required_tool_loop_detected_total : string
val metric_keeper_zombie_loop_detected_total : string
val metric_keeper_required_tool_gate_suppressed_total : string
val metric_keeper_consecutive_idle : string
val metric_keeper_last_productive_ts : string
val metric_keeper_oas_timeout_budget_strike : string
val metric_oas_bus_subscriber_stream_depth : string
val metric_oas_bus_publish_block_seconds : string
val metric_oas_bus_publish : string
val metric_runtime_ollama_probe_generate_skips : string
val metric_process_timeout : string
val metric_bg_task_sidecar_failures : string
val metric_build_identity_probe_failures : string
val metric_distributed_lock_acquire_failed : string
val metric_fs_atomic_orphans_cleaned : string
val metric_auth_bearer_token_mismatch : string
val metric_auth_strict_unknown_tool_denials : string
val metric_auth_credential_token_duplicate : string
val metric_auth_credential_token_rotated : string
val metric_config_credential_archived_starvation : string
val metric_auth_credential_ambiguous_lookup : string
val metric_silent_auth_token_resolve_error : string
val metric_silent_dashboard_actor_fallback : string
val metric_auth_strict_would_reject : string
val metric_empty_tool_universe_observed : string
val metric_coord_join_normalize_outcome : string
val metric_config_unknown_keys_ignored : string
val metric_governance_judge_unparseable : string
val metric_governance_lenient_json_fallback_hit : string
val metric_keeper_stale_termination_total : string
val metric_keeper_stale_termination_by_class : string
val metric_keeper_oas_timeout_budget_watchdog_termination : string
val metric_keeper_stale_termination_threshold_breached : string
val metric_keeper_stale_termination_batch : string
val metric_keeper_stale_broadcast_emit_failures : string
val metric_keeper_oas_run_timeout : string
val metric_keeper_tool_use_failure : string
val metric_keeper_tool_not_allowed : string
val metric_after_turn_response_model_empty : string
val metric_after_turn_response_model_alias : string
val metric_pricing_catalog_miss : string
val metric_cost_emit_zero_source : string
val metric_cost_ledger_status : string
val metric_keeper_turn_gate_rejected_terminal : string
val metric_keeper_receipt_unmapped_disposition : string
val metric_keeper_bash_network_upgrade : string
val metric_keeper_bash_local_execution : string
val metric_keeper_docker_runtime_discarded : string
val metric_keeper_proactive_skip : string
val metric_keeper_stay_silent_loop_detected : string
val metric_keeper_usage_trust : string
val metric_keeper_usage_anomaly_reason : string
val metric_keeper_config_env_parse_failures : string
val metric_keeper_post_turn_wirein_failures : string
val metric_keeper_recurring_failures : string
val metric_keeper_turn_cleanup_failures : string
val metric_mention_dedup_decisions_total : string
