(** Private Prometheus metric-name constants. *)

val metric_codex_cli_mcp_tool_omission : string
val metric_telemetry_coverage_gap : string
val metric_telemetry_unified_source_read_failures : string
val metric_tool_assignment_telemetry_failures : string
val metric_telemetry_observe_failures : string
val metric_coord_telemetry_drop : string
val metric_coord_claim_post_provision_failures : string
val metric_oas_bridge_timeout : string
val metric_oas_bridge_cancel : string
val metric_oas_sse_relay_retries : string
val metric_oas_sse_relay_drops : string
val metric_oas_sse_relay_queue_depth : string
val metric_oas_inference_telemetry_tokens : string
val metric_oas_inference_prompt_tok_per_sec : string
val metric_oas_inference_decode_tok_per_sec : string
val metric_oas_inference_cost_usd : string
val metric_cascade_provider_health_score : string
val metric_oas_context_overflow_ratio : string
val metric_oas_context_compaction_total : string
val metric_mcp_tool_schema_count : string
val metric_mcp_tool_schema_tokens_approx : string
val metric_sse_sessions : string
val metric_sse_broadcast_duration : string
val metric_sse_broadcast_events : string
val metric_sse_broadcast_failures : string
val metric_sse_external_subscriber_callback_failures : string
val metric_oas_sse_relay_drop_marker_failures : string
val metric_sse_stream_queue_depth : string
val metric_sse_queue_depth_avg : string
val metric_sse_queue_depth_max : string
val metric_sse_external_subscribers : string
val metric_sse_client_evictions : string
val metric_coord_broadcast_duration : string
val metric_file_lock_retries : string
val metric_file_lock_acquire_duration : string
val metric_grpc_active_streams : string
val metric_grpc_heartbeat_latency : string
val metric_grpc_subscribers : string
val metric_grpc_events_delivered : string
val metric_grpc_events_dropped : string
val metric_ws_sessions : string
val metric_ws_parse_cache_hits : string
val metric_ws_parse_cache_misses : string
val metric_ws_bytes_cache_hits : string
val metric_ws_bytes_cache_misses : string
val metric_dashboard_execution_render_phase_sec : string
val metric_dashboard_snapshot_latency_seconds : string
val metric_dashboard_snapshot_latency_seconds_bucket : string
val metric_dashboard_metric_all_zeros : string
val metric_cache_hits_total : string
val metric_cache_misses_total : string
val metric_ws_client_buffered_bytes : string
val metric_ws_client_acks : string
val metric_ws_throttled_deliveries : string
val metric_ws_slice_fanout_skipped : string
val metric_ws_bytes_sent : string
val metric_grpc_bytes_sent : string
val metric_ws_delta_built : string
val metric_ws_message_bytes : string
val metric_grpc_backlog_replay_lines_scanned : string
val metric_grpc_backlog_replay_events_replayed : string
val metric_http_accepts : string
val metric_http_accept_errors : string
val metric_http_active_connections : string
val metric_inference_queue_depth : string
val metric_inference_queue_inflight : string
val metric_inference_queue_acquired : string
val metric_inference_queue_wait : string
val metric_inference_queue_cancelled : string
val metric_inference_queue_rejected : string
val metric_inference_queue_max_concurrent : string
val metric_agent_heartbeat_age_seconds : string
val metric_agent_stale_total : string
val metric_open_fds : string
val metric_fd_warn_threshold : string
val metric_mcp_requests : string
val metric_llm_inference_duration : string
val metric_llm_prompt_tok_per_sec : string
val metric_llm_decode_tok_per_sec : string
val metric_cascade_ttfb_seconds : string
val metric_cascade_inter_chunk_seconds : string
val metric_after_turn_hook : string
val metric_keeper_oas_on_stop : string
val metric_keeper_oas_on_idle_escalated : string
val metric_after_turn_telemetry_missing : string
val metric_after_turn_telemetry_zero_latency : string
val metric_tasks : string
val metric_errors : string
val metric_error_events : string
val metric_workspace_route_failures : string
val metric_active_agents : string
val metric_pending_tasks : string
val metric_uptime_seconds : string
val metric_goal_attainment_pct : string
val metric_goal_attainment_measured : string
val metric_gc_minor_words : string
val metric_gc_major_words : string
val metric_gc_heap_words : string
val metric_gc_live_words : string
val metric_gc_compactions : string
val metric_gc_promoted_words : string
val metric_memory_usage_bytes : string
val metric_sse_connections_active : string
val metric_sse_reconnects : string
val metric_sse_idle_evictions : string
val metric_sse_capacity_evictions : string
val metric_sse_write_failures : string
val metric_sse_rejects : string
val metric_provider_prefix_cache_creation_tokens : string
val metric_provider_prefix_cache_read_tokens : string
val metric_tool_call : string
val metric_tool_call_duration : string
val metric_llm_provider_http_status : string
val metric_llm_provider_request_latency : string
val metric_llm_provider_request_latency_clamped : string
val metric_llm_provider_capability_drops : string
val metric_llm_provider_cache_hits : string
val metric_llm_provider_cache_misses : string
val metric_llm_provider_requests_started : string
val metric_llm_provider_errors : string
val metric_llm_provider_errors_by_reason : string
val metric_llm_provider_retries : string
val metric_llm_provider_input_tokens : string
val metric_llm_provider_output_tokens : string
val metric_fallback_triggered : string
val metric_anti_rationalization_fallback : string
val metric_anti_rationalization_excuse_pattern : string
val metric_board_truncated_posts : string
val metric_keeper_quantitative_claim_rejections : string
val metric_cascade_strategy_decisions : string
val metric_cascade_capacity_events : string
val metric_cascade_attempt_liveness_kill : string
val metric_cascade_attempt_liveness_observed : string
val metric_keeper_invariant_violations : string
val metric_keeper_fsm_edge_transitions : string
val metric_keeper_turn_fsm_transitions : string
val metric_keeper_turn_phase_duration : string
val metric_keeper_lifecycle_transitions : string
val metric_fsm_guard_violation : string
val metric_keeper_lifecycle_callback_failures : string
val metric_memory_pipeline_flushes : string
val metric_memory_pipeline_flush_records : string
val metric_memory_pipeline_flush_duration_seconds : string
val metric_keeper_event_bus_drain : string
val metric_keeper_supervisor_cleanup_failures : string
val metric_keeper_slot_force_released : string
val metric_keeper_registry_update_dropped : string
val metric_keeper_registry_orphan_threshold_breached : string
val metric_keeper_stale_watchdog_tick_failures : string
val metric_keeper_dead_total : string
val metric_keeper_auto_resumed_total : string
val metric_keeper_auto_resume_blocked_total : string
val metric_keeper_skip_idle_wake_resumed : string
val metric_keeper_event_queue_override : string
val metric_keeper_stimulus_consumed : string
val metric_keeper_unsupported_stimulus : string
val metric_keeper_near_exhaustion_total : string
val metric_keeper_restart_attempts : string
val metric_keeper_restart_outcomes : string
val metric_keeper_liveness_recovery_attempts : string
val metric_keeper_liveness_recovery_outcomes : string
val metric_cascade_server_error_skip_total : string
val metric_cascade_fallback_cycle_detected_total : string
val metric_provider_health_probe_skipped : string
val metric_provider_actual_health_status : string
