(** Private Prometheus metric-name constants. *)

val metric_keeper_turns : string
val metric_keeper_input_tokens : string
val metric_keeper_output_tokens : string
val metric_keeper_cache_creation_tokens : string
val metric_keeper_cache_read_tokens : string
val metric_keeper_usage_anomalies : string
val metric_keeper_total_cost_usd : string
val metric_keeper_turn_scheduled : string
val metric_keeper_turn_completed : string
val metric_keeper_idle_seconds : string
val metric_keeper_contract_violations : string
val metric_keeper_alive_but_stuck : string
val metric_keeper_alive_but_stuck_seconds : string
val metric_keeper_alive_but_stuck_threshold_seconds : string
val metric_keeper_alive_but_stuck_recovery_requests : string
val metric_keeper_alive_but_stuck_recovery : string
val metric_keeper_metric_emit_dropped : string
val metric_keeper_context_max_observed : string
val metric_keeper_turn_starts : string
val metric_keeper_turn_reattempts : string
val metric_keeper_turn_regressions : string
val metric_keeper_turn_livelock_blocks : string
val metric_keeper_turn_latency_bucket : string
val metric_keeper_turn_latency_by_model_bucket : string
val metric_keeper_provider_cooldown_skip : string
val metric_keeper_provider_cooldown_remaining_sec : string
val metric_keeper_provider_block_duration_sec : string
val metric_board_persist_lock_acquire_sec : string
val metric_board_persist_lock_held_sec : string
val metric_backend_mutex_acquire_sec : string
val metric_backend_mutex_held_sec : string
val metric_keeper_turn_queue_depth : string
val metric_keeper_supervisor_sweep_starts : string
val metric_keeper_supervisor_last_sweep_unixtime : string
val metric_tool_join_required_guard : string
val metric_keeper_semaphore_wait_timeout : string
val metric_keeper_turn_slot_bookkeeping_failures : string
val metric_keeper_semaphore_wait_seconds : string
val metric_keeper_semaphore_wait_seconds_bucket : string
val metric_keeper_slot_yield_total : string
val metric_timeout_policy_overshoot : string
val metric_keeper_compactions : string
val metric_keeper_compaction_ratio_change : string
val metric_keeper_compaction_saved_tokens : string
val metric_keeper_operator_compact : string
val metric_keeper_operator_clear : string
val metric_keeper_compaction_noop : string
val metric_keeper_tool_emission_registry_size : string
val metric_keeper_tool_emission_pushes : string
val metric_keeper_tool_underused_allowed_count : string
val metric_keeper_tool_underused_allowed : string
val metric_keeper_path_rejection : string
val metric_keeper_admission_shadow_outcome : string
val metric_keeper_heartbeat_successes : string
val metric_keeper_heartbeat_failures : string
val metric_keeper_cleanup_tracking_failures : string
val metric_keeper_dispatch_event_failures : string
val metric_keeper_directive_failures : string
val metric_keeper_tool_call_duration : string
val metric_keeper_write_meta_failures : string
val metric_write_meta_cas_retry_total : string
val metric_keeper_meta_read_failures : string
val metric_keeper_approval_queue_failures : string
val metric_keeper_guards_failures : string
val metric_keeper_profile_load_failures : string
val metric_keeper_compact_audit_failures : string
val metric_keeper_fs_failures : string
val metric_keeper_crash_persistence_failures : string
val metric_keeper_generation_lineage_failures : string
val metric_keeper_keepalive_signal_failures : string
val metric_keeper_board_signal_no_wake_total : string
val metric_keeper_meta_json_failures : string
val metric_keeper_tools_oas_failures : string
val metric_keeper_oas_hook_output_parse_failures : string
val metric_keeper_turn_up_update_failures : string
val metric_keeper_exec_tools_failures : string
val metric_keeper_circuit_breaker_trips : string
val metric_keeper_prompt_failures : string
val metric_keeper_run_context_failures : string
val metric_keeper_shell_ops_failures : string
val metric_keeper_tag_dispatch_failures : string
val metric_keeper_trace_emit_failures : string
val metric_keeper_transition_audit_failures : string
val metric_keeper_execution_receipt_failures : string
val metric_keeper_llm_bridge_failures : string
val metric_keeper_shell_bash_failures : string
val metric_keeper_rollover_failures : string
val metric_keeper_lifecycle_dispatch_rejections : string
val metric_keeper_paused_state_persist_errors : string
val metric_keeper_unexpected_tool_partial_tolerance : string
val metric_keeper_require_tool_use_violations : string
val metric_keeper_tool_alias_canonicalizations : string
val metric_keeper_profile_config_conflicts : string
val metric_keeper_oas_timeout_classifications : string
val metric_keeper_no_tool_provider : string
val metric_keeper_proactive_outcome : string
val metric_keeper_ollama_saturation_skip : string
val metric_keeper_task_load_failures : string
val metric_keeper_tool_selection_failures : string
val metric_keeper_tool_policy_failures : string
val metric_tool_policy_unloaded_query : string
val metric_tool_policy_init_failed : string
val metric_cache_desync_cleared : string
val metric_keeper_reconcile_failures : string
val metric_keeper_decision_audit_flush_failures : string
val metric_keeper_oas_cancel : string
val metric_keeper_claim_auto_provision : string
val metric_egress_audit_missing : string
val metric_egress_audit_stale_orphan : string
val metric_keeper_toml_invalid : string
val metric_keeper_persona_drift_missing : string
val metric_keeper_room_init_failures : string
val metric_keeper_presence_sync_failures : string
val metric_keeper_self_preservation_universal : string
val metric_keeper_stale_storm_paused : string
val metric_keeper_stale_fleet_batch_paused : string
val metric_keeper_oas_timeout_budget_loop_paused : string
val metric_keeper_cycle_exceptions : string
val metric_keeper_snapshot_write_failures : string
val metric_keeper_progress_updated_line_failures : string
val metric_keeper_sse_broadcast_failures : string
val metric_keeper_room_heartbeat_failures : string
val metric_keeper_turn_metrics_snapshot_failures : string
val metric_keeper_oas_execution_errors : string
val metric_keeper_episode_create_failures : string
val metric_keeper_memory_activity_emit_failures : string
val metric_keeper_supervisor_sweep_failures : string
val metric_keeper_toml_reconcile_sweep_failures : string
val metric_keeper_tool_usage_flush_failures : string
val metric_keeper_turn_timeout_committed : string
val metric_keeper_turn_error_after_tools : string
val metric_keeper_cascade_sync_failures : string
val metric_keeper_local_discovery_failures : string
val metric_keeper_thinking_persist_failures : string
val metric_keeper_checkpoint_failures : string
val metric_keeper_memory_write_failures : string
val metric_keeper_memory_consolidations : string
val metric_keeper_write_meta_cycle_failures : string
val metric_keeper_alert_persist_failures : string
val metric_keeper_metrics_sse_failures : string
val metric_keeper_session_cleanup_failures : string
val metric_keeper_chat_store_failures : string
val metric_keeper_observation_query_failures : string
val metric_persistence_read_drops : string
val metric_persistence_utf8_repair : string
val metric_discovery_history_failures : string
