module Format = Stdlib.Format
module Map = Stdlib.Map
module Set = Stdlib.Set
module Queue = Stdlib.Queue
module Hashtbl = Stdlib.Hashtbl
module Mutex = Stdlib.Mutex
module Option = Stdlib.Option
module Result = Stdlib.Result
module Sys = Stdlib.Sys
module Filename = Stdlib.Filename
module List = Stdlib.List
module Array = Stdlib.Array
module String = Stdlib.String
module Char = Stdlib.Char
module Int = Stdlib.Int
module Float = Stdlib.Float
module Random = Stdlib.Random

(** Reputation — Reputation scoring from existing JSONL data

    Computes agent reputation from task transitions, mention inbox,
    and board posts/comments.
    No new storage — reads from existing `.masc/` JSONL files.

    @since Phase 3B — Keeper Deliberation Engine
*)

type agent_reputation = {
  agent_name: string;
  tasks_completed: int; [@default 0]
  tasks_claimed: int; [@default 0]
  completion_rate: float; [@default 0.0]
  mentions_received: int; [@default 0]
  mentions_responded: int; [@default 0]
  response_rate: float; [@default 0.0]
  board_posts: int; [@default 0]
  board_comments: int; [@default 0]
  accountability_score: float; [@default 1.0]
  accountability_risk_band: string; [@default "low"]
  accountability_evidence_coverage: float; [@default 1.0]
  accountability_unsupported_completion_rate: float; [@default 0.0]
  accountability_open_overdue_commitments: int; [@default 0]
  accountability_keeper_name: string; [@default ""]
  accountability_source: string; [@default "none"]
  accountability_source_label: string; [@default "No accountability history"]
  (* v2 multi-dimensional scores — additive fields; absent in v1 records
     are interpreted as the neutral default (1.0 for rates, "standard" for level). *)
  execution_reliability: float; [@default 1.0]
  (** Tool-call success rate from the v2 ledger. 0.0–1.0. *)
  goal_adherence: float; [@default 1.0]
  (** Proportion of goal completions that were on-topic and within budget. 0.0–1.0. *)
  safety_compliance: float; [@default 1.0]
  (** Penalty-adjusted safety score; decreases with each sandbox violation. 0.0–1.0. *)
  autonomy_level: string; [@default "standard"]
  (** Derived autonomy envelope: "restricted" | "standard" | "elevated" | "full". *)
  thompson_confidence: float; [@default 0.5]
  (** Thompson Sampling Beta expected value (alpha/(alpha+beta)).
      0.5 is the neutral prior (alpha=1.0, beta=1.0). *)
  evidence_state: string; [@default "default"]
} [@@deriving yojson { strict = false }]

(** {1 Defaults} *)

let default_reputation ~(agent_name : string) : agent_reputation =
  { agent_name;
    tasks_completed = 0;
    tasks_claimed = 0;
    completion_rate = 0.0;
    mentions_received = 0;
    mentions_responded = 0;
    response_rate = 0.0;
    board_posts = 0;
    board_comments = 0;
    accountability_score = 1.0;
    accountability_risk_band = "low";
    accountability_evidence_coverage = 1.0;
    accountability_unsupported_completion_rate = 0.0;
    accountability_open_overdue_commitments = 0;
    accountability_keeper_name = agent_name;
    accountability_source = "none";
    accountability_source_label = "No accountability history";
    execution_reliability = 1.0;
    goal_adherence = 1.0;
    safety_compliance = 1.0;
    autonomy_level = "standard";
    thompson_confidence = 0.5;
    evidence_state = "default";
  }

(** {1 JSON Serialization}

    [agent_reputation_to_yojson] and [agent_reputation_of_yojson] are
    generated by [ppx_deriving_yojson].  The wrappers below preserve
    the legacy [option]-returning API for callers that haven't migrated
    to [result] yet. *)

let reputation_to_json : agent_reputation -> Yojson.Safe.t =
  agent_reputation_to_yojson

let reputation_of_json (json : Yojson.Safe.t) : agent_reputation option =
  match agent_reputation_of_yojson json with
  | Ok r when not (String.equal r.agent_name "") -> Some r
  | Ok _ -> None
  | Error msg ->
    Log.Reputation.warn "agent reputation of_json: %s" msg;
    None

(** {1 JSONL Helpers} *)

(** Load a JSONL file, filter out malformed lines. *)
let load_jsonl_safe (path : string) : Yojson.Safe.t list =
  if not (Sys.file_exists path) then []
  else
    match Safe_ops.read_file_safe path with
    | Error msg ->
        Log.Misc.warn "agent_reputation: failed to read %s: %s" path msg;
        []
    | Ok content ->
      String.split_on_char '\n' content
      |> List.filter (fun line -> String.length (String.trim line) > 0)
      |> List.filter_map (fun line ->
          try Some (Yojson.Safe.from_string line)
          with Yojson.Json_error _ -> None)

(** {1 Task Counting from Workspace State} *)

(** Canonical keeper name used for identity comparison.  Shared with
    {!accountability_metrics} so both metrics fold an identity the same way:
    via [Keeper_identity.canonical_keeper_name_from_agent_name], which unwraps
    the full actor id and resolves a generated-nickname alias to its agent
    type, falling back to the trimmed input for non-keeper principals.

    Known residual: this canonicalizer collapses 3+-part hyphenated non-keeper
    ids (e.g. "codex-mcp-client" -> "client") onto their last segment, so such
    principals can share a canonical form.  Resolving that needs registry-aware
    typed identity (RFC-0038 Phase 2); it does not affect single-token keeper
    names, which are the subject of the undercount fixed below. *)
let keeper_name_of_agent agent_name =
  match Keeper_identity.canonical_keeper_name_from_agent_name agent_name with
  | Some keeper_name -> keeper_name
  | None -> String.trim agent_name

(** Count tasks claimed and completed by an agent from the task backlog.
    Reads the canonical Workspace backlog so reputation follows the same storage
    path as task transitions.

    Identity is compared on the canonical keeper name (see
    {!keeper_name_of_agent}).  Previously a raw [String.equal assignee
    agent_name] was used: because the backlog persists [assignee] as the full
    actor id the claiming keeper used ("keeper-taskmaster-agent") while
    reputation is computed per short handle ("taskmaster"), every full-actor-id
    row was silently dropped, undercounting a keeper's claims/completions. *)
let count_tasks_from_backlog (config : Workspace.config) ~(agent_name : string)
    : int * int =
  let owner = keeper_name_of_agent agent_name in
  let assignee_is_owner assignee =
    String.equal (keeper_name_of_agent assignee) owner
  in
  let claimed = ref 0 in
  let completed = ref 0 in
  Workspace.get_tasks_safe config
  |> List.iter (fun (task : Masc_domain.task) ->
         match task.task_status with
         | Masc_domain.Claimed { assignee; _ }
         | Masc_domain.InProgress { assignee; _ }
         | Masc_domain.AwaitingVerification { assignee; _ }
           when assignee_is_owner assignee ->
             Stdlib.incr claimed
         | Masc_domain.Done { assignee; _ } when assignee_is_owner assignee ->
             Stdlib.incr claimed;
             Stdlib.incr completed
         | Masc_domain.Todo
         | Masc_domain.Claimed _ | Masc_domain.InProgress _ | Masc_domain.AwaitingVerification _
         | Masc_domain.Done _ | Masc_domain.Cancelled _ -> ());
  (!claimed, !completed)

(** {1 Board Counting} *)

(* Board activity counts feed contributor-quality on the board dashboard,
   where [compute_reputation] is invoked once per unique post author in a
   single render. The previous implementation re-read and re-parsed
   board_posts.jsonl (~3.4MB) and board_comments.jsonl (~1.6MB) on every
   call, making one board render O(authors x full-file-parse) — measured at
   ~1.7s for ~50 authors against the live runtime.

   We parse each file once and project an author -> (posts, comments) count
   table, refreshed only when a source file's mtime changes. One [stat] per
   call (microseconds) gates the cache, so the per-author calls in a render
   and warm refresh loops reuse the parse. mtime gating (rather than a
   file-watch daemon) keeps the projection correct under external multi-agent
   appends without adding load to fseventsd. *)
let board_activity_cache :
    (string, int * int) Hashtbl.t Jsonl_mtime_projection.t =
  Jsonl_mtime_projection.create ()

let build_board_activity_counts ~posts_path ~comments_path :
    (string, int * int) Hashtbl.t =
  let by_author : (string, int * int) Hashtbl.t = Hashtbl.create 256 in
  let tally select rows =
    List.iter
      (fun json ->
        let author = Safe_ops.json_string ~default:"" "author" json in
        let posts, comments =
          Hashtbl.find_opt by_author author |> Option.value ~default:(0, 0)
        in
        Hashtbl.replace by_author author (select (posts, comments)))
      rows
  in
  tally (fun (p, c) -> (p + 1, c)) (load_jsonl_safe posts_path);
  tally (fun (p, c) -> (p, c + 1)) (load_jsonl_safe comments_path);
  by_author

(* Return the author -> (posts, comments) projection, rebuilding only when a
   source file's (mtime, size) signature changes. Keyed on the board directory;
   the shared [Jsonl_mtime_projection] performs the stat-gated reuse and is the
   appropriate tool here because the board JSONL files change rarely relative to
   render volume (unlike the streamed keeper feeds, which use the incremental
   projection). *)
let board_activity_table board_dir : (string, int * int) Hashtbl.t =
  let posts_path = Filename.concat board_dir "board_posts.jsonl" in
  let comments_path = Filename.concat board_dir "board_comments.jsonl" in
  Jsonl_mtime_projection.get board_activity_cache ~key:board_dir
    ~sources:[ posts_path; comments_path ]
    ~build:(fun () -> build_board_activity_counts ~posts_path ~comments_path)

(** Count board posts and comments authored by an agent under [board_dir].

    Served from an mtime-gated projection of board_posts.jsonl and
    board_comments.jsonl (see {!board_activity_table}). The result is identical
    to filtering each file by [author = agent_name] but amortizes the parse
    across every author queried while the files are unchanged. Exposed without
    the [Workspace.config] indirection so the projection can be tested directly. *)
let count_board_activity_in_dir ~(board_dir : string) ~(agent_name : string) :
    int * int =
  Hashtbl.find_opt (board_activity_table board_dir) agent_name
  |> Option.value ~default:(0, 0)

(** Count board posts and comments authored by an agent. *)
let count_board_activity (config : Workspace.config) ~(agent_name : string)
    : int * int =
  count_board_activity_in_dir ~board_dir:(Workspace.masc_dir config) ~agent_name

(** {1 Mention Counting} *)

let count_mention_activity (config : Workspace.config) ~(agent_name : string)
    : int * int =
  let all = Mention_inbox.read_mentions config ~target_agent:agent_name ~limit:10000 in
  let received = List.length all in
  let responded = List_util.count_if (fun r -> Stdlib.Float.compare r.Mention_inbox.read_at 0.0 > 0) all in
  (received, responded)

(** {1 Overall Score Computation} *)

let clamp01 value = Float.max 0.0 (Float.min 1.0 value)

let compute_accountability_score ~evidence_coverage
    ~unsupported_completion_rate ~open_overdue_commitments : float =
  let overdue_penalty =
    Float.min 0.5 (0.1 *. Float.of_int open_overdue_commitments)
  in
  clamp01
    (evidence_coverage -. unsupported_completion_rate -. overdue_penalty)

(** {1 Accountability Penalty} *)

let accountability_metrics (config : Workspace.config) ~(agent_name : string) =
  let keeper_name = keeper_name_of_agent agent_name in
  let summary =
    Keeper_accountability.accountability_summary_json config
      ~keeper_name ~agent_name
  in
  let evidence_coverage =
    Safe_ops.json_float ~default:1.0 "evidence_coverage" summary
  in
  let unsupported_completion_rate =
    Safe_ops.json_float ~default:0.0 "unsupported_completion_rate" summary
  in
  let open_overdue_commitments =
    Safe_ops.json_int ~default:0 "open_overdue_commitments" summary
  in
  let risk_band =
    Safe_ops.json_string ~default:"low" "risk_band" summary
  in
  let source =
    Safe_ops.json_string ~default:"none" "source" summary
  in
  let source_label =
    Safe_ops.json_string ~default:"No accountability history" "source_label"
      summary
  in
  let score =
    compute_accountability_score ~evidence_coverage
      ~unsupported_completion_rate ~open_overdue_commitments
  in
  (score, risk_band, evidence_coverage, unsupported_completion_rate,
   open_overdue_commitments, keeper_name, source, source_label)

(** {1 Main Computation} *)

(** Default window for v2 ledger metrics: 14 days matches accountability window. *)
let v2_ledger_window_days = 14

(** {1 Thompson Confidence}

    Compute the Thompson Sampling Beta expected value for an agent.
    Returns 0.5 (neutral prior) when no stats exist or when alpha+beta
    is zero (should not happen given min 0.1 priors, but safe division
    handles the edge case). *)
let thompson_confidence_for_agent (agent_name : string) : float =
  let stats = Thompson_sampling.get_stats agent_name in
  let sum = stats.Thompson_sampling.alpha +. stats.Thompson_sampling.beta in
  if sum > 0.0 then stats.Thompson_sampling.alpha /. sum
  else 0.5

let compute_reputation (config : Workspace.config) ~(agent_name : string)
    : agent_reputation =
  let (tasks_claimed, tasks_completed) =
    count_tasks_from_backlog config ~agent_name
  in
  let completion_rate =
    if tasks_claimed > 0 then
      Float.of_int tasks_completed /. Float.of_int tasks_claimed
    else 0.0
  in
  let (mentions_received, mentions_responded) =
    count_mention_activity config ~agent_name
  in
  let response_rate =
    if mentions_received > 0 then
      Float.of_int mentions_responded /. Float.of_int mentions_received
    else 0.0
  in
  let (board_posts, board_comments) = count_board_activity config ~agent_name in
  let (accountability_score, accountability_risk_band,
       accountability_evidence_coverage,
       accountability_unsupported_completion_rate,
       accountability_open_overdue_commitments,
       accountability_keeper_name,
       accountability_source,
       accountability_source_label) =
    accountability_metrics config ~agent_name
  in
  let thompson_confidence = thompson_confidence_for_agent agent_name in
  (* v2: pull multi-dimensional metrics from the reputation ledger. *)
  let v2_metrics =
    (try
       Reputation_ledger_v2.compute_ledger_metrics config
         ~agent_id:agent_name ~window_days:v2_ledger_window_days
     with
     | Eio.Cancel.Cancelled _ as e -> raise e
     | _exn ->
       Reputation_ledger_v2.default_ledger_metrics)
  in
  let autonomy =
    Reputation_autonomy.compute_autonomy_level
      ~execution_reliability:v2_metrics.Reputation_ledger_v2.execution_reliability
      ~goal_adherence:v2_metrics.Reputation_ledger_v2.goal_adherence
      ~safety_compliance:v2_metrics.Reputation_ledger_v2.safety_compliance
      ~accountability_score:(clamp01 accountability_score)
  in
  let has_evidence =
    tasks_claimed > 0
    || mentions_received > 0
    || board_posts > 0
    || board_comments > 0
    || accountability_source <> "none"
    || v2_metrics.Reputation_ledger_v2.tool_calls > 0
    || v2_metrics.Reputation_ledger_v2.goal_completions > 0
    || v2_metrics.Reputation_ledger_v2.safety_violations > 0
    || (let stats = Thompson_sampling.get_stats agent_name in
        stats.Thompson_sampling.total_votes_up > 0
        || stats.Thompson_sampling.total_votes_down > 0
        || stats.Thompson_sampling.selections > 0)
  in
  let evidence_state = if has_evidence then "measured" else "default" in
  { agent_name;
    tasks_completed; tasks_claimed; completion_rate;
    mentions_received; mentions_responded; response_rate;
    board_posts; board_comments;
    accountability_score;
    accountability_risk_band;
    accountability_evidence_coverage;
    accountability_unsupported_completion_rate;
    accountability_open_overdue_commitments;
    accountability_keeper_name;
    accountability_source;
    accountability_source_label;
    execution_reliability = v2_metrics.Reputation_ledger_v2.execution_reliability;
    goal_adherence = v2_metrics.Reputation_ledger_v2.goal_adherence;
    safety_compliance = v2_metrics.Reputation_ledger_v2.safety_compliance;
    autonomy_level = Reputation_autonomy.autonomy_level_to_string autonomy;
    thompson_confidence;
    evidence_state;
  }
