open Tool_command_plane_support
open Tool_command_plane_mutations
open Tool_command_plane_operations

let dispatch (ctx : (_, _) context) ~name ~args : tool_result option =
  match name with
  | "masc_unit_define" -> Some (handle_unit_define ctx args)
  | "masc_unit_list" -> Some (handle_unit_list ctx)
  | "masc_unit_reparent" -> Some (handle_unit_reparent ctx args)
  | "masc_unit_reassign" -> Some (handle_unit_reassign ctx args)
  | "masc_operation_start" -> Some (handle_operation_start ctx args)
  | "masc_operation_status" -> Some (handle_operation_status ctx args)
  | "masc_operation_checkpoint" -> Some (handle_operation_checkpoint ctx args)
  | "masc_operation_pause" -> Some (handle_operation_pause ctx args)
  | "masc_operation_resume" -> Some (handle_operation_resume ctx args)
  | "masc_operation_stop" -> Some (handle_operation_stop ctx args)
  | "masc_operation_finalize" -> Some (handle_operation_finalize ctx args)
  | "masc_dispatch_plan" -> Some (handle_dispatch_plan ctx args)
  | "masc_dispatch_assign" -> Some (handle_dispatch_assign ctx args)
  | "masc_dispatch_rebalance" -> Some (handle_dispatch_rebalance ctx args)
  | "masc_dispatch_escalate" -> Some (handle_dispatch_escalate ctx args)
  | "masc_dispatch_recall" -> Some (handle_dispatch_recall ctx args)
  | "masc_dispatch_tick" -> Some (handle_dispatch_tick ctx args)
  | "masc_policy_status" -> Some (handle_policy_status ctx)
  | "masc_policy_approve" -> Some (handle_policy_approve ctx args)
  | "masc_policy_deny" -> Some (handle_policy_deny ctx args)
  | "masc_policy_update" -> Some (handle_policy_update ctx args)
  | "masc_policy_freeze_unit" -> Some (handle_policy_freeze_unit ctx args)
  | "masc_policy_kill_switch" -> Some (handle_policy_kill_switch ctx args)
  | "masc_observe_topology" -> Some (handle_observe_topology ctx)
  | "masc_observe_alerts" -> Some (handle_observe_alerts ctx)
  | "masc_observe_operations" -> Some (handle_observe_operations ctx)
  | "masc_observe_swarm" -> Some (handle_observe_swarm ctx args)
  | "masc_observe_capacity" -> Some (handle_observe_capacity ctx)
  | "masc_observe_traces" -> Some (handle_observe_traces ctx args)
  | "masc_intent_create" -> Some (handle_intent_create ctx args)
  | "masc_intent_status" -> Some (handle_intent_status ctx args)
  | "masc_intent_update" -> Some (handle_intent_update ctx args)
  | "masc_intent_forecast" -> Some (handle_intent_forecast ctx args)
  | _ -> None
