(** Keeper domain metrics. *)

type t =
  | Turns
  | InputTokens
  | OutputTokens
  | CacheCreationTokens
  | CacheReadTokens
  | UsageAnomalies
  | TotalCostUsd
  | TurnScheduled
  | TurnCompleted
  | IdleSeconds
  | ContractViolations
  | MetricEmitDropped
  | ContextMaxObserved
  | TurnStarts
  | TurnReattempts
  | TurnRegressions
  | TurnLivelockBlocks
  | TurnLivelockBlocksRepeated
  | TurnLivelockBlocksThresholdPark
  | TurnLatencyBucket
  | TurnLatencyByModelBucket
  | ProviderCooldownSkip
  | ProviderCooldownRemainingSec
  | ProviderBlockDurationSec
  | TurnQueueDepth
  | SupervisorSweepStarts
  | SupervisorLastSweepUnixtime
  | DomainPoolFork
  | SemaphoreWaitTimeout
  | TurnSlotBookkeepingFailures
  | SemaphoreWaitSeconds
  | SemaphoreWaitSecondsBucket
  | SlotYieldTotal
  | Compactions
  | CompactionRatioChange
  | CompactionSavedTokens
  | CompactionPairRepairFabrications
  | EmergencyCompactRatioThreshold
  | OperatorCompact
  | OperatorClear
  | CompactionNoop
  | ContinuityNoState
  | ToolPairRepair
  | ToolEmissionRegistrySize
  | ToolEmissionPushes
  | ToolUnderusedAllowedCount
  | ToolUnderusedAllowed
  | PathRejection
  | IdeOrphanWrites
  | PathResolverIdentityMismatch
  | HeartbeatSuccesses
  | HeartbeatFailures
  | CleanupTrackingFailures
  | DispatchEventFailures
  | DirectiveFailures
  | ToolCallDuration
  | WriteMetaFailures
  | MetaReadFailures
  | ApprovalQueueFailures
  | GuardsFailures
  | ProfileLoadFailures
  | CompactAuditFailures
  | CompactAuditRetentionParse
  | CompactAuditDrainBatches
  | CompactAuditDrainBatchSizeBucket
  | FsFailures
  | CrashPersistenceFailures
  | GenerationLineageFailures
  | KeepaliveSignalFailures
  | BoardSignalWakeupCappedTotal
  | BoardSignalNoWakeTotal
  | MetaJsonFailures
  | ToolsOasFailures
  | ToolsOasDeterministicFailures
  | TurnUpUpdateFailures
  | AgentToolDispatchRuntimeFailures
  | CircuitBreakerTrips
  | PromptFailures
  | RunContextFailures
  | SearchFilesFailures
  | TagDispatchFailures
  | TraceEmitFailures
  | TransitionAuditFailures
  | ExecutionReceiptFailures
  | OperatorBroadcastSuppressed
  | LlmBridgeFailures
  | SessionCleanupFailures
  | ToolExecuteFailures
  | RolloverFailures
  | LifecycleDispatchRejections
  | RecordingErrorDedup
  | PausedStatePersistErrors
  | UnexpectedToolPartialTolerance
  | ToolCallTotal
  | ProfileConfigConflicts
  | OasTimeoutClassifications
  | NoToolProvider
  | ProactiveOutcome
  | OllamaSaturationSkip
  | TaskLoadFailures
  | ToolSelectionFailures
  | ToolPolicyFailures
  | ReconcileFailures
  | DecisionAuditFlushFailures
  | OasCancel
  | ClaimAutoProvision
  | TomlInvalid
  | PersonaDriftMissing
  | WorkspaceInitFailures
  | PresenceSyncFailures
  | SelfPreservationUniversal
  | StaleStormPaused
  | ProviderTimeoutLoopPaused
  | CycleExceptions
  | SnapshotWriteFailures
  | StateSnapshotSkippedNoState
  | ProgressUpdatedLineFailures
  | SseBroadcastFailures
  | WorkspaceHeartbeatFailures
  | TurnMetricsSnapshotFailures
  | OasExecutionErrors
  | EpisodeCreateFailures
  | MemoryActivityEmitFailures
  | SupervisorSweepFailures
  | TomlReconcileSweepFailures
  | TomlReconcileDedup
  | ReconcileDisabled
  | ToolUsageFlushFailures
  | TurnTimeoutCommitted
  | TurnErrorAfterTools
  | RuntimeSyncFailures
  | LocalDiscoveryFailures
  | ThinkingPersistFailures
  | CheckpointFailures
  | DecisionAuditRingOverflows
  | ReplySkillRouteStrips
  | ReplySkillRouteLinesRemoved
  | MemoryLlmSummaryOutcomes
  | MemoryLlmSummaryChainExhausted
  | UserVisibleReplySource
  | ContinuitySummarySource
  | SummarizerStateScrubs
  | SummarizerStateBlocksRemoved
  | OasEnvKeyRejections
  | ContinuityTsRecovered
  | MemoryWriteFailures
  | MemoryConsolidations
  | WriteMetaCycleFailures
  | AlertPersistFailures
  | MetricsSseFailures
  | ChatStoreFailures
  | ObservationQueryFailures
  | OasOnStop
  | OasOnIdleEscalated
  | InvariantViolations
  | FsmEdgeTransitions
  | TurnFsmTransitions
  | TurnPhaseDuration
  | LifecycleTransitions
  | LifecycleCallbackFailures
  | CompactionCallbackRecoveries
  | EventBusDrain
  | SupervisorCleanupFailures
  | SlotForceReleased
  | SpawnSlotDenied
  | RegistryUpdateDropped
  | RegistryOrphanThresholdBreached
  | DeadTotal
  | AutoResumedTotal
  | AutoResumeBlockedTotal
  | SkipIdleWakeResumed
  | EventQueueOverride
  | StimulusConsumed
  | UnsupportedStimulus
  | NearExhaustionTotal
  | RestartAttempts
  | RestartOutcomes
  | ConsecutiveIdle
  | LastProductiveTs
  | ProviderTimeoutStrike
  | StaleTerminationTotal
  | StaleTerminationByClass
  | ProviderTimeoutWatchdogTermination
  | StaleTerminationThresholdBreached
  | StaleTerminationBatch
  | StaleBroadcastEmitFailures
  | OasRunTimeout
  | RuntimeSaturationSignal
  | ToolUseFailure
  | ToolNotAllowed
  | TurnGateRejectedTerminal
  | ReceiptUnmappedDisposition
  | ExecuteNetworkUpgrade
  | ExecuteLocalExecution
  | DockerRuntimeDiscarded
  | ProactiveSkip
  | StaySilentLoopDetected
  | UsageTrust
  | UsageAnomalyReason
  | ConfigEnvParseFailures
  | PostTurnWireinFailures
  | RecurringFailures
  | TurnCleanupFailures
  | MemoryBankLoadHistorySwallowedExceptions
  | MemoryRecallReadErrors
  | RuntimeHttpProbeJsonParseFailures

val to_string : t -> string
