#!/usr/bin/env bash
# check-opam-file-regenerated.sh
#
# CI gate: verify that the checked-in masc.opam is byte-identical to what
# dune regenerates from dune-project.
#
# Rationale: dune-project carries `(generate_opam_files true)`, so masc.opam
# is a generated artifact — opam solve reads the generated file, not
# dune-project. #36410 edited dune-project's `(ocaml ...)` constraint without
# regenerating masc.opam, so the PR's stated purpose (letting the 5.5.0 lane
# build) never reached the file opam actually reads, and the drift passed
# every gate silently. The existing guards compare masc.opam against the
# sandbox image (check-sandbox-ocaml-version.sh) and the version truth
# (check-version-truth.sh); none of them compares the generated file with
# its source. This closes that third gap at PR time.
#
# Where it runs: this check needs the OCaml switch (`dune build masc.opam`
# regenerates the file), so it is wired as a step in the "dune build @check"
# job of pr-check.yml — next to the two #34018 guards that were moved there
# for the same reason — and NOT into the toolchain-free lint suite.
#
# How it works: `dune build masc.opam` regenerates masc.opam in the source
# tree, overwriting the checked-in file. So the check snapshots the committed
# bytes BEFORE regenerating, regenerates, and compares the regenerated bytes
# against that snapshot — a stale checked-in file shows up as a diff. It then
# leaves the regenerated file in place (that is the fix a failing PR needs to
# commit), so the worktree is dirty exactly when the gate is red.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

committed_opam="$repo_root/masc.opam"

if [[ ! -f "$committed_opam" ]]; then
  printf 'FAIL: no checked-in masc.opam at repo root\n' >&2
  exit 1
fi

if ! grep -Fq '(generate_opam_files true)' dune-project; then
  printf 'FAIL: dune-project no longer declares (generate_opam_files true)\n' >&2
  printf '  This guard assumes the generated-file workflow.\n' >&2
  exit 1
fi

# Snapshot the committed bytes BEFORE regenerating: dune writes the
# regenerated file over the checked-in one, so this copy is the only
# record of what the PR actually ships.
snapshot="$(mktemp)"
regeneration_log="$(mktemp)"
trap 'rm -f "$snapshot" "$regeneration_log"' EXIT
cp "$committed_opam" "$snapshot"

# Regenerate. The local wrapper serializes concurrent dune runs and injects
# --root; the two skips keep the check independent of the local switch's
# exact compiler and of optional pins, which is what CI needs.
if ! MASC_SKIP_OCAML_VERSION_CHECK=1 MASC_SKIP_DEPS_CHECK=1 \
       scripts/dune-local.sh build masc.opam >"$regeneration_log" 2>&1; then
  printf 'FAIL: regenerating masc.opam failed\n' >&2
  printf '  ran: MASC_SKIP_OCAML_VERSION_CHECK=1 MASC_SKIP_DEPS_CHECK=1 scripts/dune-local.sh build masc.opam\n' >&2
  printf '\n' >&2
  # Without this the only thing a red CI run says is that regeneration
  # failed, and the dune error that says why is gone.
  printf '  What it printed (last 40 lines):\n' >&2
  sed 's/^/  /' "$regeneration_log" | tail -40 >&2
  exit 1
fi

if [[ ! -f "$committed_opam" ]]; then
  printf 'FAIL: regeneration removed masc.opam from the source tree\n' >&2
  exit 1
fi

if ! cmp -s "$committed_opam" "$snapshot"; then
  printf 'FAIL: masc.opam was stale — dune-project and the committed masc.opam had drifted\n' >&2
  printf '  dune-project was edited without regenerating the opam file that\n' >&2
  printf '  opam solve actually reads (the #36410 failure mode).\n' >&2
  printf '  Fix: commit the regenerated masc.opam that this check just wrote\n' >&2
  printf '  (it is already in the worktree), or run `dune build masc.opam` again\n' >&2
  printf '  after fixing dune-project.\n' >&2
  printf '\n' >&2
  printf '  Diff (regenerated vs previously committed):\n' >&2
  diff "$committed_opam" "$snapshot" | head -40 >&2 || true
  exit 1
fi

printf 'OK: masc.opam matches dune-project regeneration\n'