#!/usr/bin/env bash
# gen-research-index.sh — Generate docs/research/README.md from the research tree.
#
# Reads:
#   docs/research/*.md   every record except README.md itself
#   first "# " heading   the record's title
#   filename prefix      the record's date (YYYY-MM-DD)
# Writes (to stdout):
#   a markdown index, newest first, one row per record.
#
# Usage:
#   scripts/gen-research-index.sh > docs/research/README.md
#
# Exit codes:
#   0  index emitted
#   2  docs/research missing
#
# Dependencies: bash, find, awk, sort. No new tools.

set -euo pipefail

DIR="$(cd "$(dirname "$0")/../docs/research" && pwd)"

if [ ! -d "$DIR" ]; then
  echo "gen-research-index.sh: $DIR not found" >&2
  exit 2
fi

echo "# Research Records"
echo
echo "<!-- Generated by scripts/gen-research-index.sh. Do not edit by hand;"
echo "     regenerate with: scripts/gen-research-index.sh > docs/research/README.md -->"
echo
echo "Measurement records and research syntheses, one row per file. A"
echo "\`*-evidence-record.md\` names its paired run files (\`*-r1.md\`,"
echo "\`*-runtime-*.md\`); raw benchmark outputs they cite live under"
echo "\`benchmarks/context_recovery/results/\`."
echo
echo "| Date | Record |"
echo "| --- | --- |"

find "$DIR" -maxdepth 1 -name '*.md' ! -name 'README.md' | sort -r | while IFS= read -r f; do
  base="$(basename "$f")"
  date="${base:0:10}"
  if [[ ! "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    date="—"
  fi
  title="$(awk '/^# /{sub(/^# +/,""); gsub(/\|/,"\\\\|"); print; exit}' "$f")"
  if [ -z "$title" ]; then
    title="$base"
  fi
  echo "| $date | [$title]($base) |"
done
