#!/usr/bin/env python3
"""Generate the OCaml terminal-reason catalog from JSON."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


VALID_SEVERITIES = {"ok", "warn", "bad"}


def ocaml_string(value: str) -> str:
    return (
        '"'
        + value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        + '"'
    )


def require_string(obj: dict[str, Any], key: str) -> str:
    value = obj.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{key} must be a non-empty string")
    return value


def validate_catalog(raw: dict[str, Any]) -> None:
    if raw.get("schema_version") != 1:
        raise ValueError("schema_version must be 1")

    reasons = raw.get("reasons")
    if not isinstance(reasons, list) or not reasons:
        raise ValueError("reasons must be a non-empty list")

    codes: set[str] = set()
    for entry in reasons:
        if not isinstance(entry, dict):
            raise ValueError("reason entries must be objects")
        code = require_string(entry, "code")
        if code in codes:
            raise ValueError(f"duplicate reason code: {code}")
        codes.add(code)
        severity = require_string(entry, "severity")
        if severity not in VALID_SEVERITIES:
            raise ValueError(f"invalid severity for {code}: {severity}")
        require_string(entry, "summary")
        next_action = entry.get("next_action")
        if next_action is not None and (
            not isinstance(next_action, str) or not next_action.strip()
        ):
            raise ValueError(f"next_action for {code} must be null or non-empty string")

    aliases = raw.get("aliases", [])
    if not isinstance(aliases, list):
        raise ValueError("aliases must be a list")
    alias_sources: set[str] = set()
    for alias in aliases:
        if not isinstance(alias, dict):
            raise ValueError("alias entries must be objects")
        source = require_string(alias, "from")
        target = require_string(alias, "to")
        if source in alias_sources:
            raise ValueError(f"duplicate alias source: {source}")
        alias_sources.add(source)
        if target not in codes:
            raise ValueError(
                f"alias target is not a catalog reason: {source} -> {target}"
            )

    prefixes = raw.get("severity_prefixes", [])
    if not isinstance(prefixes, list):
        raise ValueError("severity_prefixes must be a list")
    seen_prefixes: set[str] = set()
    for prefix_entry in prefixes:
        if not isinstance(prefix_entry, dict):
            raise ValueError("severity_prefix entries must be objects")
        prefix = require_string(prefix_entry, "prefix")
        if prefix in seen_prefixes:
            raise ValueError(f"duplicate severity prefix: {prefix}")
        seen_prefixes.add(prefix)
        severity = require_string(prefix_entry, "severity")
        if severity not in VALID_SEVERITIES:
            raise ValueError(f"invalid severity for prefix {prefix}: {severity}")


def generate(raw: dict[str, Any]) -> str:
    lines: list[str] = [
        "(* This file is generated by scripts/gen_keeper_turn_terminal_catalog.py.",
        "   Edit config/keeper_turn_terminal_reasons.json instead. *)",
        "",
        "type reason =",
        "  { code : string",
        "  ; severity : string",
        "  ; summary : string",
        "  ; next_action : string option",
        "  }",
        "",
        "let reasons =",
        "  [",
    ]
    for entry in raw["reasons"]:
        next_action = entry.get("next_action")
        next_action_expr = (
            "None" if next_action is None else f"Some {ocaml_string(next_action)}"
        )
        lines.extend(
            [
                "    { code = "
                + ocaml_string(entry["code"])
                + "; severity = "
                + ocaml_string(entry["severity"])
                + "; summary = "
                + ocaml_string(entry["summary"])
                + "; next_action = "
                + next_action_expr
                + " };",
            ]
        )
    lines.extend(["  ]", "", "let aliases =", "  ["])
    for alias in raw.get("aliases", []):
        lines.append(
            "    ("
            + ocaml_string(alias["from"])
            + ", "
            + ocaml_string(alias["to"])
            + ");"
        )
    lines.extend(["  ]", "", "let severity_prefixes =", "  ["])
    for prefix in raw.get("severity_prefixes", []):
        lines.append(
            "    ("
            + ocaml_string(prefix["prefix"])
            + ", "
            + ocaml_string(prefix["severity"])
            + ");"
        )
    lines.extend(["  ]", ""])
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: gen_keeper_turn_terminal_catalog.py <catalog.json> <out.ml>",
            file=sys.stderr,
        )
        return 2
    source = Path(sys.argv[1])
    target = Path(sys.argv[2])
    raw = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("catalog root must be an object")
    validate_catalog(raw)
    target.write_text(generate(raw), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
