import type { DashboardScheduledAutomationRequest, DashboardScheduledAutomationSignal } from '../../api'

const baseTime = new Date()
baseTime.setHours(14, 0, 0, 0)

export const MOCK_SCHEDULES: DashboardScheduledAutomationRequest[] = [
  {
    schedule_id: 'sch_9f2a',
    status: 'pending_approval',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'nick0cave', kind: 'keeper' },
    risk_class: 'workspace_write',
    approval_required: true,
    recurrence: { kind: 'one_shot' },
    payload_kind: 'keeper.start',
    payload_summary: 'core/scheduler 야간 회귀 스위트 실행 (round jitter 재측정)',
    due_at_iso: new Date(baseTime.getTime() + 41400 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 1200 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 86400 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_b714',
    status: 'pending_approval',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'drifter', kind: 'keeper' },
    risk_class: 'cost_bearing',
    approval_required: true,
    recurrence: { kind: 'daily', hour: 2, minute: 0, timezone: 'KST' },
    payload_kind: 'index.reindex',
    payload_summary: 'search/index 전체 재색인 — 야간 윈도우, 예상 $4.20',
    due_at_iso: new Date(baseTime.getTime() + 41400 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 3600 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 86400 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_c081',
    status: 'pending_approval',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'analyst', kind: 'keeper' },
    risk_class: 'external_write',
    approval_required: true,
    recurrence: { kind: 'daily', hour: 9, minute: 0, timezone: 'KST' },
    payload_kind: 'report.generate',
    payload_summary: '리텐션 주간 리포트 생성 후 Slack #kidsnote-growth 게시',
    due_at_iso: new Date(baseTime.getTime() + 66600 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 4800 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 86400 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_4d3e',
    status: 'scheduled',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'masc-improver', kind: 'keeper' },
    risk_class: 'read_only',
    approval_required: false,
    recurrence: { kind: 'interval', interval_sec: 21600 },
    payload_kind: 'compact.sweep',
    payload_summary: 'lib/trace-store 컨텍스트 스윕 — 85% 초과 keeper 자동 compact',
    due_at_iso: new Date(baseTime.getTime() + 15120 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 7200 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 30000 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_77a0',
    status: 'due',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'sangsu', kind: 'keeper' },
    risk_class: 'read_only',
    approval_required: false,
    recurrence: { kind: 'interval', interval_sec: 3600 },
    payload_kind: 'gate.recheck',
    payload_summary: '커넥터 게이트 헬스 재점검 (slack · discord · amplitude)',
    due_at_iso: new Date(baseTime.getTime() - 40 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 3640 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 560 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_2e55',
    status: 'running',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'qa-king', kind: 'keeper' },
    risk_class: 'workspace_write',
    approval_required: false,
    recurrence: { kind: 'one_shot' },
    payload_kind: 'report.generate',
    payload_summary: 'docs/site 링크 점검 리포트 — PR 프리뷰 검증',
    due_at_iso: new Date(baseTime.getTime() - 120 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 2000 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 3600 * 1000).toISOString(),
    last_execution: {
      execution_id: 'exec-1',
      schedule_id: 'sch_2e55',
      status: 'running',
      started_at_iso: new Date(baseTime.getTime() - 120 * 1000).toISOString(),
    },
  },
  {
    schedule_id: 'sch_18bc',
    status: 'succeeded',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'masc-improver', kind: 'keeper' },
    risk_class: 'read_only',
    approval_required: false,
    recurrence: { kind: 'interval', interval_sec: 5400 },
    payload_kind: 'trace.export',
    payload_summary: 'trace 윈도우 내보내기 → s3://masc-traces',
    due_at_iso: new Date(baseTime.getTime() - 1800 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 7200 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 3600 * 1000).toISOString(),
    last_execution: {
      execution_id: 'exec-2',
      schedule_id: 'sch_18bc',
      status: 'succeeded',
      started_at_iso: new Date(baseTime.getTime() - 1800 * 1000).toISOString(),
      finished_at_iso: new Date(baseTime.getTime() - 1800 * 1000).toISOString(),
    },
  },
  {
    schedule_id: 'sch_a93f',
    status: 'failed',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'nick0cave', kind: 'keeper' },
    risk_class: 'workspace_write',
    approval_required: true,
    recurrence: { kind: 'one_shot' },
    payload_kind: 'keeper.start',
    payload_summary: 'compact-lock 재현 잡 기동 — runtime 연결 실패',
    due_at_iso: new Date(baseTime.getTime() - 10800 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 12000 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 3600 * 1000).toISOString(),
    last_execution: {
      execution_id: 'exec-3',
      schedule_id: 'sch_a93f',
      status: 'failed',
      started_at_iso: new Date(baseTime.getTime() - 10800 * 1000).toISOString(),
      finished_at_iso: new Date(baseTime.getTime() - 10800 * 1000).toISOString(),
      error: 'runtime oas·tokyo-2 연결 거부 (fallback 소진)',
    },
  },
  {
    schedule_id: 'sch_55d1',
    status: 'rejected',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'drifter', kind: 'keeper' },
    risk_class: 'destructive',
    approval_required: true,
    recurrence: { kind: 'one_shot' },
    payload_kind: 'archive.purge',
    payload_summary: 'archive 네임스페이스 30일 경과 항목 영구 삭제',
    due_at_iso: new Date(baseTime.getTime() + 99999 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 10000 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 86400 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_30c8',
    status: 'cancelled',
    source: 'operator_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'reviewer', kind: 'keeper' },
    risk_class: 'external_write',
    approval_required: true,
    recurrence: { kind: 'daily', hour: 18, minute: 0, timezone: 'KST' },
    payload_kind: 'broadcast.send',
    payload_summary: '일일 옵저버토리 요약 브로드캐스트',
    due_at_iso: new Date(baseTime.getTime() + 99999 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 20000 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() + 86400 * 1000).toISOString(),
  },
  {
    schedule_id: 'sch_71fa',
    status: 'expired',
    source: 'automated_request',
    requested_by: { id: 'operator', kind: 'operator' },
    scheduled_by: { id: 'scholar', kind: 'keeper' },
    risk_class: 'reminder_only',
    approval_required: false,
    recurrence: { kind: 'one_shot' },
    payload_kind: 'gate.recheck',
    payload_summary: 'iMessage 게이트 재점검 리마인더 — 승인 창 경과',
    due_at_iso: new Date(baseTime.getTime() - 7200 * 1000).toISOString(),
    requested_at_iso: new Date(baseTime.getTime() - 10000 * 1000).toISOString(),
    expires_at_iso: new Date(baseTime.getTime() - 1000 * 1000).toISOString(),
  },
]

export const MOCK_SIGNALS: DashboardScheduledAutomationSignal[] = [
  {
    signal_id: 'sig_4a21',
    kind: 'due_candidate',
    schedule_id: 'sch_77a0',
    emitted_at_iso: new Date(baseTime.getTime() - 40 * 1000).toISOString(),
    risk_class: 'read_only',
  },
  {
    signal_id: 'sig_4a18',
    kind: 'due_blocked_approval',
    schedule_id: 'sch_a93f',
    emitted_at_iso: new Date(baseTime.getTime() - 10800 * 1000).toISOString(),
    risk_class: 'workspace_write',
  },
  {
    signal_id: 'sig_49f7',
    kind: 'due_candidate',
    schedule_id: 'sch_18bc',
    emitted_at_iso: new Date(baseTime.getTime() - 1800 * 1000).toISOString(),
    risk_class: 'read_only',
  },
  {
    signal_id: 'sig_49e0',
    kind: 'due_candidate',
    schedule_id: 'sch_2e55',
    emitted_at_iso: new Date(baseTime.getTime() - 120 * 1000).toISOString(),
    risk_class: 'workspace_write',
  },
]

export const MOCK_KEEPER_BG = [
  { id: 'bg_p01', keeper: 'masc-improver', kind: 'poll', label: 'board 새 post·comment 감시', cadence_sec: 30,  status: 'running', risk_class: 'read_only', since: '09:12' },
  { id: 'bg_p02', keeper: 'qa-king',       kind: 'poll', label: 'git worktree fetch · origin/main', cadence_sec: 300, status: 'running', risk_class: 'read_only', since: '11:40' },
  { id: 'bg_p03', keeper: 'nick0cave',     kind: 'poll', label: 'LSP diagnostics watch · round.ml', cadence_sec: 60,  status: 'running', risk_class: 'read_only', since: '13:20' },
  { id: 'bg_p04', keeper: 'sangsu',        kind: 'poll', label: 'connector gate heartbeat', cadence_sec: 120, status: 'paused',  risk_class: 'read_only', since: '—' },
  { id: 'bg_a01', keeper: 'masc-improver', kind: 'async_tool', label: 'tool_execute · 회귀 스위트 빌드', tool: 'tool_execute', status: 'in_flight', risk_class: 'workspace_write', issued: '13:58', eta: '~2m' },
  { id: 'bg_a02', keeper: 'analyst',       kind: 'async_tool', label: 'amplitude 쿼리 · retention 30d', tool: 'mcp.amplitude', status: 'awaiting',  risk_class: 'external_write', issued: '13:55', eta: '응답 대기' },
  { id: 'bg_a03', keeper: 'nick0cave',     kind: 'async_tool', label: 'MCP fetch · docs 링크 검증', tool: 'mcp.fetch', status: 'in_flight', risk_class: 'read_only', issued: '14:00', eta: '~40s' },
]
