---- MODULE KeeperTraceSpec ----
\* Validates an observed trace against KeeperStateMachine safety invariants.
\* Requires TraceData.tla to be generated by bin/trace_to_tla.exe.

EXTENDS Naturals

CONSTANTS MaxRestarts

VARIABLES
    fiber_alive, heartbeat_healthy, turn_healthy,
    compaction_active, handoff_active, operator_paused,
    stop_requested, restart_budget_remaining, backoff_elapsed,
    guardrail_triggered, drain_complete, restart_count,
    trace_idx

INSTANCE TraceData

vars == <<fiber_alive, heartbeat_healthy, turn_healthy,
          compaction_active, handoff_active, operator_paused,
          stop_requested, restart_budget_remaining, backoff_elapsed,
          guardrail_triggered, drain_complete, restart_count, trace_idx>>

\* ── Phase Derivation (copied from KeeperStateMachine) ────

DerivePhase ==
    IF stop_requested /\ drain_complete
       /\ ~compaction_active /\ ~handoff_active THEN "Stopped"
    ELSE IF ~fiber_alive /\ ~restart_budget_remaining THEN "Dead"
    ELSE IF ~fiber_alive /\ restart_budget_remaining /\ backoff_elapsed THEN "Restarting"
    ELSE IF ~fiber_alive /\ restart_budget_remaining THEN "Crashed"
    ELSE IF stop_requested THEN "Draining"
    ELSE IF guardrail_triggered THEN "Failing"
    ELSE IF operator_paused THEN "Paused"
    ELSE IF handoff_active THEN "HandingOff"
    ELSE IF compaction_active THEN "Compacting"
    ELSE IF ~heartbeat_healthy \/ ~turn_healthy THEN "Failing"
    ELSE IF fiber_alive THEN "Running"
    ELSE "Offline"

\* ── Trace Init: load first step ──────────────────────────

TraceInit ==
    /\ trace_idx = 1
    /\ fiber_alive = Trace[1].fiber_alive
    /\ heartbeat_healthy = Trace[1].heartbeat_healthy
    /\ turn_healthy = Trace[1].turn_healthy
    /\ compaction_active = Trace[1].compaction_active
    /\ handoff_active = Trace[1].handoff_active
    /\ operator_paused = Trace[1].operator_paused
    /\ stop_requested = Trace[1].stop_requested
    /\ restart_budget_remaining = Trace[1].restart_budget_remaining
    /\ backoff_elapsed = Trace[1].backoff_elapsed
    /\ guardrail_triggered = Trace[1].guardrail_triggered
    /\ drain_complete = Trace[1].drain_complete
    /\ restart_count = Trace[1].restart_count

\* ── Trace Next: step through trace ───────────────────────

TraceNext ==
    /\ trace_idx < TraceLength
    /\ trace_idx' = trace_idx + 1
    /\ fiber_alive' = Trace[trace_idx + 1].fiber_alive
    /\ heartbeat_healthy' = Trace[trace_idx + 1].heartbeat_healthy
    /\ turn_healthy' = Trace[trace_idx + 1].turn_healthy
    /\ compaction_active' = Trace[trace_idx + 1].compaction_active
    /\ handoff_active' = Trace[trace_idx + 1].handoff_active
    /\ operator_paused' = Trace[trace_idx + 1].operator_paused
    /\ stop_requested' = Trace[trace_idx + 1].stop_requested
    /\ restart_budget_remaining' = Trace[trace_idx + 1].restart_budget_remaining
    /\ backoff_elapsed' = Trace[trace_idx + 1].backoff_elapsed
    /\ guardrail_triggered' = Trace[trace_idx + 1].guardrail_triggered
    /\ drain_complete' = Trace[trace_idx + 1].drain_complete
    /\ restart_count' = Trace[trace_idx + 1].restart_count

TraceSpec == TraceInit /\ [][TraceNext]_vars

\* ── Safety Invariants ────────────────────────────────────

TypeOK ==
    /\ fiber_alive \in BOOLEAN
    /\ heartbeat_healthy \in BOOLEAN
    /\ turn_healthy \in BOOLEAN
    /\ compaction_active \in BOOLEAN
    /\ handoff_active \in BOOLEAN
    /\ operator_paused \in BOOLEAN
    /\ stop_requested \in BOOLEAN
    /\ restart_budget_remaining \in BOOLEAN
    /\ backoff_elapsed \in BOOLEAN
    /\ guardrail_triggered \in BOOLEAN
    /\ drain_complete \in BOOLEAN
    /\ restart_count \in 0..MaxRestarts+10
    /\ trace_idx \in 1..TraceLength

RunningRequiresFiber == DerivePhase = "Running" => fiber_alive
StoppedRequiresDrain == DerivePhase = "Stopped" => (stop_requested /\ drain_complete)
DeadRequiresNoBudget == DerivePhase = "Dead" => ~restart_budget_remaining

\* Monotonicity: restart_count never decreases
RestartCountMonotonic == [][restart_count' >= restart_count]_vars

\* Budget never revives
BudgetNeverRevives == [](~restart_budget_remaining => [](~restart_budget_remaining))

====
