(** Keeper domain metrics. *)

type t =
  | Turns
  | InputTokens
  | OutputTokens
  | CacheCreationTokens
  | CacheReadTokens
  | UsageAnomalies
  | TotalCostUsd
  | TurnScheduled
  | TurnCompleted
  | PacingShadowEvents
  | PacingShadowNextDueSec
  | FailureRoute
  | FailureJudgmentOutcome
  | FailureDrivenPause
  | IdleSeconds
  | ContractViolations
  | StreamProjectionEventCutoff
  | MetricEmitDropped
  | ContextMaxObserved
  | TurnStarts
  | TurnReattempts
  | TurnRegressions
  | TurnLivelockBlocks
  | TurnLivelockBlocksRepeated
  | TurnLivelockBlocksThresholdPark
  | TurnLatencyBucket
  | TurnLatencyByModelBucket
  | ProviderCooldownSkip
  | ProviderCooldownRemainingSec
  | ProviderBlockDurationSec
  | TurnQueueDepth
  | SupervisorSweepStarts
  | SupervisorLastSweepUnixtime
  | DomainPoolFork
  | TurnHolderBookkeepingFailures
  | Compactions
  | CompactionRatioChange
  | CompactionSavedTokens
  | CompactionPairRepairDrops
  | EmergencyCompactRatioThreshold
  | OperatorCompact
  | OperatorClear
  | CompactionNoop
  | ToolPairRepair
  | ToolEmissionRegistrySize
  | ToolEmissionPushes
  | ToolUnderusedAllowedCount
  | ToolUnderusedAllowed
  | PathRejection
  | IdeOrphanWrites
  | PathResolverIdentityMismatch
  | KeeperMetaOverlayDrift
  | HeartbeatSuccesses
  | HeartbeatFailures
  | CleanupTrackingFailures
  | DispatchEventFailures
  | DirectiveFailures
  | ToolCallDuration
  | ToolCallDurationBucket
  | WriteMetaFailures
  | MetaReadFailures
  | ApprovalQueueFailures
  | ApprovalResolutionSignal
  | GuardsFailures
  | ProfileLoadFailures
  | CompactAuditFailures
  | CompactAuditRetentionParse
  | CompactAuditDrainBatches
  | CompactAuditDrainBatchSizeBucket
  | FsFailures
  | CrashPersistenceFailures
  | GenerationLineageFailures
  | KeepaliveSignalFailures
  | BoardSignalWakeupCappedTotal
  | BoardSignalNoWakeTotal
  | BoardSignalAttentionCandidateTotal
  | MetaJsonFailures
  | ToolsOasFailures
  | ToolsOasDeterministicFailures
  | TurnUpUpdateFailures
  | AgentToolDispatchRuntimeFailures
  | CircuitBreakerTrips
  | PromptFailures
  | RunContextFailures
  | SearchFilesFailures
  | TagDispatchFailures
  | TraceEmitFailures
  | TransitionAuditFailures
  | ExecutionReceiptFailures
  | OperatorBroadcastSuppressed
  | LlmBridgeFailures
  | SessionCleanupFailures
  | ToolExecuteFailures
  | RolloverFailures
  | LifecycleDispatchRejections
  | LifecycleTransactions
  | RecordingErrorDedup
  | PausedStatePersistErrors
  | UnexpectedToolPartialTolerance
  | ToolCallTotal
  | ProfileConfigConflicts
  | OasTimeoutClassifications
  | NoToolProvider
  | ProactiveOutcome
  | OllamaSaturationSkip
  | TaskLoadFailures
  | ToolSelectionFailures
  | ReconcileFailures
  | DecisionAuditFlushFailures
  | OasCancel
  | ClaimAutoProvision
  | PersonaDriftMissing
  | WorkspaceInitFailures
  | PresenceSyncFailures
  | SelfPreservationUniversal
  | StaleStormPaused
  | ProviderTimeoutLoopPaused
  | TurnFailureStreakPaused
  | CycleExceptions
  | SnapshotReadFailures
  | SnapshotWriteFailures
  | PromptUnknownToolTokens
  | PromptTokenStripped
  | SseBroadcastFailures
  | WorkspaceHeartbeatFailures
  | TurnMetricsSnapshotFailures
  | OasExecutionErrors
  | EpisodeCreateFailures
  | MemoryActivityEmitFailures
  | SupervisorSweepFailures
  | TomlReconcileSweepFailures
  | TomlReconcileDedup
  | ReconcileDisabled
  | ToolUsageFlushFailures
  | TurnTimeoutCommitted
  | TurnErrorAfterTools
  | RuntimeSyncFailures
  | LocalDiscoveryFailures
  | ThinkingPersistFailures
  | CheckpointFailures
  | DecisionAuditRingOverflows
  | ReplySkillRouteStrips
  | ReplySkillRouteLinesRemoved
  | MemoryLlmSummaryOutcomes
  | MemoryLlmSummaryChainExhausted
  | HitlSummaryOutcomes
  | UserVisibleReplySource
  | OasEnvKeyRejections
  | MemoryWriteFailures
  | MemoryLaneUnitFailures
  | MemoryConsolidations
  | MemoryLaneSubmitted
  | MemoryLaneRanInline
  | MemoryLaneDropped
  | MemoryLanePending
  | MemoryLaneInFlight
  | MemoryLaneProviderSlotBusy
  | MemoryBankCompactionFailures
  | MemoryOsMaintenanceKeeperTimeout
  | WriteMetaCycleFailures
  | AlertPersistFailures
  | MetricsSseFailures
  | ChatStoreFailures
  | ChatTransportFailures
  | PersonNoteStoreFailures
  | KeeperMaterializationFailures
  | ObservationQueryFailures
  | OasOnStop
  | InvariantViolations
  | FsmEdgeTransitions
  | TurnFsmTransitions
  | TurnPhaseDuration
  | LifecycleTransitions
  | LifecycleCallbackFailures
  | CompactionCallbackRecoveries
  | EventBusDrain
  | SupervisorCleanupFailures
  | SpawnSlotDenied
  | RegistryUpdateDropped
  | RegistryOrphanThresholdBreached
  | RegistryInvalidEntry
  | DeadTotal
  | AutoResumedTotal
  | AutoResumeBlockedTotal
  | SkipIdleWakeResumed
  | EventQueueOverride
  | StimulusConsumed
  | UnsupportedStimulus
  | NearExhaustionTotal
  | RestartAttempts
  | RestartOutcomes
  | LastProductiveTs
  | ProviderTimeoutStrike
  | StaleTerminationTotal
  | StaleTerminationByClass
  | ProviderTimeoutWatchdogTermination
  | StaleTerminationThresholdBreached
  | StaleTerminationBatch
  | StaleBroadcastEmitFailures
  | OasRunTimeout
  | RuntimeSaturationSignal
  | RuntimeSelected
  | RuntimeRotation
  | ToolUseFailure
  | ToolNotAllowed
  | TurnGateRejectedTerminal
  | ReceiptUnmappedDisposition
  | ExecuteNetworkUpgrade
  | ExecuteLocalExecution
  | DockerRuntimeDiscarded
  | ProactiveSkip
  | NoProgressLoopDetected
  | NoProgressStreak
  | UsageTrust
  | UsageAnomalyReason
  | ConfigEnvParseFailures
  | PostTurnWireinFailures
  | RecurringFailures
  | TurnCleanupFailures
  | MemoryBankLoadHistorySwallowedExceptions
  | MemoryRecallReadErrors
  | MemoryOsRecallUnavailable
  | MemoryOsReobserveEchoSuppressed
  | RuntimeHttpProbeJsonParseFailures
  | VisionAnalyze
  | VisionCandidateAttempts
  | VisionIngestEvictions
  | PromptSegmentBytes
  | PromptTemplateRenderOutcome
  | ToolCallParamCompleteness
  | KeeperTurnInstructionHash
  | KeeperToolCallRetryLoop
  | AttemptWatchdogFired
  | ShellIrEffectTotal
  | ToolExecutePrActionTotal
  | GhClassificationTotal
  | GatedGhLifecycleTotal
  | GatedGhBlockTimeSeconds
  | KeeperRepoMappingDefaultScopeAllowed
  | KeeperRepoMappingDeniedUnregistered
  | KeeperRepoMappingLoadError
  | KeeperRepoMappingRepositoryIdentityMismatch
  | KeeperRepoMappingRepositoryStoreError
  | RawTraceSinkDegraded
  | WireCaptureResponseSuppressed
  | WireCaptureWriteFailures
  | WireCaptureRecordSkipped
  | ContinuationDeliveryOutcome

val to_string : t -> string

val emit_runtime_selected :
  keeper_name:string -> runtime_id:string -> fallback_reason:string -> unit

val emit_runtime_rotation :
  keeper_name:string -> from_runtime:string -> to_runtime:string -> reason:string -> unit

(** Every constructor of [t], generated from the type declaration by
    [ppx_enumerate].  Membership is compiler-maintained; list order is not a
    public contract. *)
val all : t list
